### ISSUE TITLE
Doing a "run" while the box is in background mode returns to the command line rather than streaming the logs

### ISSUE THREAD

**Issue by notxarb** [nanobox-io/nanobox#10]
Expected:

[√] APP SUCCESSFULLY BUILT /// DEV URL : nodejs-test-simple-nodejs.dev

++> STREAMING LOGS (ctrl-c to exit) >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Got:

[√] APP SUCCESSFULLY BUILT /// DEV URL : nodejs-test-simple-nodejs.dev

Note: nanobox is running in background mode. To suspend it run 'nanobox down'

**Comment by tylerflint** [comment]
This might be intended behavior. It was discussed that if background mode was requested, then we won't automatically watch files for changes or stream logs. Rather, we would just return back to the command line. 

You can optionally stream logs while in background mode with 'nanobox log'.

**Comment by sdomino** [comment]
Did we decide if this was still the intended behavior or not?

**Comment by sdomino** [comment]
added a message to help clarify behavior (https://github.com/nanobox-io/nanobox/commit/9a77a4736c9b64468a501912ca5b5c5ba9d2faa2)
