### ISSUE TITLE
Explicit declaration of mounted engines

### ISSUE THREAD

**Issue by sdomino** [nanobox-io/nanobox#101]
This is an official issue regarding https://github.com/nanobox-io/nanobox/issues/95

When nanobox detects a local engine is mounted (even a clone of a generic engine). We want to show the path to the engine. So rather than:

```
--------------------------------
   [√] LANGUAGE : python
   [√] ENGINE   : python (generic)
--------------------------------
```

maybe something like:
```
--------------------------------
   [√] LANGUAGE : python
   [√] ENGINE   : path/to/mounted/engine
--------------------------------
```

**Comment by harobed** [comment]
+1 :)

**Comment by tylerflint** [comment]
@harobed Thanks for your vote! Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
