### ISSUE TITLE
Check for NFS

### ISSUE THREAD

**Issue by sdomino** [nanobox-io/nanobox#102]
From https://github.com/nanobox-io/nanobox/issues/89

We need a more reliable way of checking that we can mount as NFS before we actually do. I'll have to look into how we can do that on osx, @glinton do you happen to know what to look for on linux? In windows we'll just have to skip this entierly.

Also, we need to check the /etc/exports to ensure there isn't going to be a conflict.

**Comment by glinton** [comment]
I'm not certain off the top of my head. Lack of an `/etc/exports` file might be a good catch-all, but that's not guaranteed as someone may have, for whatever reason, specified a custom 'exports' file in some other location.

**Comment by glinton** [comment]
I just ran into the 'nfs not supported' error after using [`nanobox`](nanobox.io) with it frequently since we switched to using nfs for 'synced_folder[s]'
```
$ nanobox dev
Nanobox is out of date, would you like to update it now (y/N)? y
+> Updating nanobox...
   10.54/10.54MB [****************************************  100.00%]
   [√] Update successful
+> Creating a nanobox
   - A fatal error occurred (See ~/.nanobox/nanobox.log for details). Exiting...

$ tail ~/.nanobox/nanobox.log
2015-11-30 15:37:30 FATAL [commands/create] vagrant.Up() failed -  - exit status 1
2015-11-30 15:37:30 *LOG* Closing log now

$ tail ~/.nanobox/apps/blobstache/vagrant.log
something about vbox kernel missing, run: `sudo vboxconfig`
```

After reinstalling virtualbox 5.0.10 (`vboxconfig` constantly failed to 'Starting VirtualBox kernel modules'), I got the same `vagrant.Up() failed - exit status 1` error (#49)

```
$ tail vagrant.log 
2015-11-30 16:14:51 ERROR It appears your machine doesn't support NFS, or there is not an
2015-11-30 16:14:51 ERROR adapter to enable NFS on this machine for Vagrant. Please verify
2015-11-30 16:14:51 ERROR that `nfsd` is installed on your machine, and try again. If you're
2015-11-30 16:14:51 ERROR on Windows, NFS isn't supported. If the problem persists, please
2015-11-30 16:14:51 ERROR contact Vagrant support.
2015-11-30 16:14:51 FATAL [commands/create] vagrant.Up() failed - exit status 1
2015-11-30 16:14:51 *LOG* Closing log now
```

Although I have been running nanobox multiple times on this same node, it suddenly failed due to missing 'nfsd'.

```
$ lsmod | grep ^nfsd
$ apt-get install nfs-kernel-server
...
# seemed to think I was repairing the nfs-kernel-server install (prompted to overwrite|update /etc/exports)
```
`vagrant reload` in my '.nanobox/app' dir and `nanobox dev` worked again, though I'm still unsure why nfsd suddenly decided to go missing, I feel this is somehow related to https://github.com/mitchellh/vagrant/issues/6532

```
$ uname -a
Linux nanoboxbox 3.13.0-68-generic #111-Ubuntu SMP Fri Nov 6 18:17:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ vagrant -v
Vagrant 1.7.4
$ vboxmanage -v
5.0.10r104061
$ lsb_release -d
Description:  Ubuntu 14.04.3 LTS
```

**Comment by yamitcar** [comment]
Hi! I trying to use nanobox in windows but y have the same issue:

this is the log from vagrant.log

2015-12-09 17:58:46 ERROR There are errors in the configuration of this machine. Please fix
2015-12-09 17:58:46 ERROR the following errors and try again:
2015-12-09 17:58:46 ERROR 2015-12-09 17:58:46 ERROR vm:
2015-12-09 17:58:46 ERROR * The host path of the shared folder is missing: E:developmentworkspacesjsmmunity-website
2015-12-09 17:58:46 ERROR

**Comment by tylerflint** [comment]
@yamitcar Thanks for sharing your findings. Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. Nanobox no longer depends on Vagrant, and so this is no longer an issue. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
