### ISSUE TITLE
Don't run 'build' on nanobox dev

### ISSUE THREAD

**Issue by Tolmark12** [nanobox-io/nanobox#104]

**Comment by tylerflint** [comment]
There is a miscommunication here. 'dev' doesn't run build and hasn't for quite a while. Sorry for the confusion.

**Comment by Tolmark12** [comment]
Cool, good to hear, so npm and other dependencies won't be installed on `nanobox dev` now, correct?

**Comment by tylerflint** [comment]
No, that’s part of the environment setup.

**Comment by tylerflint** [comment]
If your ultimate goal is to not have npm or other dependencies installed on your behalf when running in 'dev', your best bet is to modify the engine and have that portion of the setup script conditional on the payload attribute "run: false".

**Comment by Tolmark12** [comment]
cool, makes sense.
