### ISSUE TITLE
Vagrant check always fails on windows

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#115]
Recently, the check to see if vagrant and virtualbox exist has been changed to the built-in LookPath function: https://github.com/nanobox-io/nanobox/blob/master/util/vagrant/vagrant.go#L28

This doesn't work on windows. Looking through the source code of the LookPath implementation for windows, I can't see why this would fail: https://golang.org/src/os/exec/lp_windows.go

**Comment by Flat** [comment]
LookPath works fine on windows to find vagrant, so it's somewhere else in the code. I'm not proficient in Go, but a quick check using

```Go
package main

import (
	"fmt"
	"os/exec"

)

func main() {
	var err error
	var path string
	if path, err = exec.LookPath("vagrant"); err == nil {
		fmt.Printf("Vagrant found at %s\n", path)
	}else{
		fmt.Printf("Vagrant not found")
	}
	
}
```
Output:
```
Vagrant found at C:\HashiCorp\Vagrant\bin\vagrant.exe
> Elapsed: 1.707s
> Result: Success
```

So I would assume it's a clause somewhere else that is making this fail.

**Comment by tylerflint** [comment]
@Flat Thanks for looking into this! 

A new windows installer the the most up-to-date version of nanobox will be up shortly. I'll give that a try and see if perhaps this isn't an issue anymore. 

Thanks again!

**Comment by tylerflint** [comment]
Confirmed. This issue is resolved in the latest release of nanobox.
