### ISSUE TITLE
Second 'nanobox dev' kills the first session and forces a re-build of the environment.

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#117]
After a successful 'nanobox dev', I was attempting to open a second 'dev' session to troubleshoot a process that was started in the first session. I expected to be dropped into the same dev container as the first dev session. Instead, the first session was interrupted and the dev1 container was destroyed. Lastly, the second 'dev' forced a rebuild which doesn't seem necessary at all.

**Comment by tylerflint** [comment]
I just confirmed, this behavior is consistent and will happen every time. It might be worth noting that in this instance I am using a local engine. I'm not sure if that tries to hijack the process somehow?

**Comment by Flat** [comment]
What operating system are you attempting this on? On Windows 10 using the most up to date code I'm able to have multiple console sessions running using nanobox dev on the same project.
![1449717874izl](https://cloud.githubusercontent.com/assets/2048861/11706109/cd848066-9ec3-11e5-9098-dc47d2c1b2c9.png)

**Comment by tylerflint** [comment]
@Flat That is really cool! I can't say that I've seen multiple dev consoles working on windows like that. Pretty cool to see it working.

Given this new information, I'm going to assume the issue is directly related to using a local engine.

@sdomino perhaps the process of creating the engine from the overlays is forcing a rebuild, which in turns kills the active session?

**Comment by sdomino** [comment]
I believe this issue is directly related to #138, I'll be starting work on both this week.
