### ISSUE TITLE
nanobox update fails on windows

### ISSUE THREAD

**Issue by Flat** [nanobox-io/nanobox#118]
nanobox update will fail on window 100% of the time due to how it replaces the CLI. 

On windows files cannot be accessed while they are running. Therefore the currently running CLI cannot overwrite itself with the new update. There are a couple solutions to this that I can think of. 

1. You can set the file to be overwritten on reboot.
2. A second program(or script) can be run that will do the step of replacing the old CLI with the new one.

**Comment by sdomino** [comment]
We're going to pull the update functionality out of nanobox and into it's own little script. This should solve this issue, as well as alleviate some other issues we've been having with the update process. Thanks for bringing this up.
