### ISSUE TITLE
Zero-configuration dev mode

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#124]
### The Problem

The 'dev' container environment is auto-configured and the source code from the host is mounted into the dev container. As part of the preparation, engines may configure required services like redis or postgres. By design, nanobox will not alter the source code on the host in any way. The usability challenge that this issue is intended to address is that as a result of nanobox being non-obtrusive, 'nanobox dev' can't auto-generate application configuration. If nanobox were to modify or generate application configuration files, those changes would be pushed back onto the original source, thus violating our strict non-obtrusive contract.

In summary, an application using nanobox in dev mode will require the developer to modify the configuration manually in order to connect to the auto-generated services within nanobox. This is in direct conflict with our zero-configuration goal.

#### Conceptually

I propose a solution that would allow the engine to generate the configuration files as it would in run mode. When the dev container is created, those generated configuration files are bind mounted on top of the original configuration files. This would allow the application within the dev container to connect to the auto-generated services, without requiring manual intervention and without modifying the source files.

#### Practically

After discussing this with other team members, it seems appropriate and courteous not to just do this silently, as the amount of perceived 'black magic' would be a concern. Not to mention, the developer would likely be frustrated to understand how their application is connecting to the services, without any evidence in the source code that they see.

The suggested approach would be twofold: inform early and allow opt-out. This would introduce a message/confirmation combination at the first 'nanobox dev' run. The message would inform the necessity for nanobox to bind mount the auto-generated config files, and ask to proceed or opt out. @Tolmark12 will provide the message/dialogue design.

### Implementation

Each of the steps below will be delegated as individual issues on their respective projects, after a general consensus has been agreed upon.

#### nanobox cli

1. Will need to add an app-specific configuration attribute: dev_config. The value will be either none, mount, or copy.
2. Will need to prompt a dialogue on 'nanobox dev' when the aforementioned attribute 'dev_config' is not set. The user response should set the value in the app config. This dialogue should be the first thing done in this subcommand.
3. Will need to accept a --dev-config=value flag that will end-run the dialogue and set the value directly.
4. Will need to pass the dev_config value as a post body when creating a dev session with nanobox server.

#### nanobox server

1. Will rename the current 'console' Boxfile node to 'dev'.
2. Will call an additional script when configuring a dev container: 'dev-prepare'. The 'dev-prepare' script should be run after the existing scripts run. The payload of this script should have a 'boxfile' attribute, which will contain the contents of the 'dev' section of the Boxfile. Also the 'dev_config' attribute should be present with the value that was provided by the cli during the dev session post.
4. The 'dev1' docker container payload will need to include the build directory from the boot2docker host at /mnt/build.
5. All scripts will be run during a deploy, regardless of dev or run mode.

#### docker-build

1. Will need a new script 'dev-prepare'. The script will accept the payload as introduced above. If the value of dev_config is 'none' then the script will do nothing. If the value is 'mount' then the script will look for the 'config_files' node within the 'boxfile' payload, and bind mount each of the entries. If the value is 'copy' then script will copy each of the values in the 'config_files' node into the raw source instead of bind mounting. The files provided in the 'config_files' node will be available within the build, which should be available at /mnt/build.

#### engines

1. Each engine will have the option of creating a 'dev' node in the boxfile bin script. The files that need to be placed in the dev container for proper configuration need to be specified in the 'config_files' node. 

Here is trivial example that might represent a rails app:

```yaml
dev:
  config_files:
    - config/database.yml
    - config/initializers/redis.rb
```

It is assumed that if the engine will provide a file in the 'config_files' node, then that file was auto-generated during the build bin script and copied into the live dir.

**Comment by lyondhill** [comment]
nanobox-server is ready for testing. it has been uploaded to the --dev version

**Comment by tylerflint** [comment]
After some usability discussions with @Tolmark12, a slight pivot on the user interaction has been suggested. The concern is that by initially prompting a decision from the user on the first 'nanobox dev', the user might implicitly wonder if they've done something wrong or if they are in the right place.

The suggested solution is a slight variation of the initial proposal. Instead of prompting a decision, we would continue on and use the default 'mount' option for the dev_config attribute. Before the mounting actually occurs, we will show a message explaining 1) what is happening 2) that we are defaulting to 'mount' 3) that they can change that value in the .nanofile and 4) which files will be affected.

This would alter the implementation in the following ways:

### nanobox-cli

1. Would not provide a prompt
2. Would not store the attribute in the app config
3. Would look for a value in the .nanofile
4. Would use 'mount' when no value is provided

### docker-build

1. Would provide the enhanced message as explained above.

**Comment by sdomino** [comment]
Where do we want to handle unexpected input (ie. we expect "mount", "none", or "copy". what happens if someone types in "asdf" as the flag)?

I'm guessing I would catch that in the CLI and either display some type of error message, or tell them im just defaulting to "mount"?

**Comment by tylerflint** [comment]
That's a good point. I think we should validate it in the cli and fail if it's not an expected value.

**Comment by sdomino** [comment]
CLI portion implemented in #128

**Comment by lyondhill** [comment]
In order to display the output from the new dev-prepare hook to the user We need to separate the /develop route form the /exec route when creating a new dev container. 

New client side dev workflow:
1 post to /develop and leave the connection open until you want the container to die.
2 read the chuncked body from the develop request and output that to the user
3 post to /exec using the tcp connection the same way as any other exec but specify dev1 as the container name

New Server side dev workflow:
1 Accept develop requests but do not hijack the request. 
2 output all hook data to the body of the request
3 wait for closenotify and then delete the container.
(exec on the server side remains the same)

**Comment by sdomino** [comment]
Output has been added to hooks that needs to be displayed to the client. Currently `nanobox dev` does not connect to Mist to display this output.

The following changes need to be made to the dev command:
1. A Mist connection (to logs) will be opened at the start of the command

The following changes need to be made to the server.exec function:
2. The request to nanobox server (POST /develop) will be made first
3. The client will then wait until it manually reads the first message from the request before continuing (all the while streaming logs from an open mist connection).
4. Once a message is received, mist needs to be closed, and the "terminal header" output can be displayed, subsequently dropping the user into their raw terminal.

The following changes need to be made to mist:
1. A new function that creates a remote client, go routines the listening stuff, and returns the client to allow for it to be manually closed.

**Comment by sdomino** [comment]
#134 contains the changes required from above
