### ISSUE TITLE
Converge tcp/udp services into web

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#127]
### The Problem

Currently, code services can be one of web, worker, tcp, or udp. The evolving landscape of web is proving that many applications provide multiple services within the same code service. It is common for an application to provide a udp or tcp service, coupled with an api. In this case, an application would have to run the same code in 2 or more services.

### The Solution

I propose that we merge tcp and udp services into the web service. The specific protocol can be determined in the 'ports' Boxfile attribute. The following is an example of a web service that exposes both http and tcp services:

```yaml
web1:
  ports:
    - tcp:9000
    - http:80:8080
    - https:443:8080
```

As shown above, the port definition is broken into 3 parts separated by a colon: PROTOCOL:EXTERNAL_PORT:INTERNAL_PORT

If the protocol is omitted, tcp will be used.

If the internal port is omitted, the external port will be used.

#### nanobox-server

The entirety of this implementation will be accomplished within the nanobox-server project. 

#### nanodocs

The following docs will need to be updated to reflect the new functionality:

https://docs.nanobox.io/getting-started/services/
https://docs.nanobox.io/boxfile/code-services/
https://docs.nanobox.io/boxfile/code-services/web/

The following docs will need to be removed:

https://docs.nanobox.io/boxfile/code-services/tcp/
https://docs.nanobox.io/boxfile/code-services/udp/

**Comment by tylerflint** [comment]
@lyondhill @sanderson please review

**Comment by lyondhill** [comment]
The Documentation needs an update
