### ISSUE TITLE
nanobox dev panic

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#135]
2015-12-23 11:43:07 FATAL Cause of failure: close of closed channel
2015-12-23 11:43:07 FATAL Error output:
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/main.go:24 (0x4002c73)
/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:437 (0x405ae4e)
/usr/local/Cellar/go/1.5.2/libexec/src/runtime/panic.go:423 (0x402b649)
/usr/local/Cellar/go/1.5.2/libexec/src/runtime/chan.go:303 (0x4005c9e)
/Users/sdomino/gocode/src/github.com/nanopack/mist/core/remote.go:201 (0x41d6c88)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/server/develop.go:27 (0x40ef44a)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/dev.go:109 (0x40854ec)
/Users/sdomino/godeps/src/github.com/spf13/cobra/command.go:547 (0x40fb389)
/Users/sdomino/godeps/src/github.com/spf13/cobra/command.go:630 (0x40fbb4a)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/main.go:40 (0x4002bba)
/usr/local/Cellar/go/1.5.2/libexec/src/runtime/proc.go:111 (0x402db30)
/usr/local/Cellar/go/1.5.2/libexec/src/runtime/asm_amd64.s:1721 (0x405d1a1)

**Comment by sdomino** [comment]
fixed by #136
