### ISSUE TITLE
Cannot start nanobox on Windows

### ISSUE THREAD

**Issue by suyashbansal** [nanobox-io/nanobox#139]
When I try 'nanobox dev' on windows, it gives a fatal error!

![image](https://cloud.githubusercontent.com/assets/5832436/12702054/9b548a7a-c842-11e5-9935-3b92acd8a97e.png)

I checked the log an it was something like this...

![image](https://cloud.githubusercontent.com/assets/5832436/12702061/ea13b726-c842-11e5-9c66-16ceab2f6dca.png)

What to do?

**Comment by HLDahquan** [comment]
I ran into the same problem and managed to get it running by manually installing vagrant.

**Comment by dubcanada** [comment]
Install vagrant and run the vagrant command from command line will created the required .vagrant.d folder. A simple install of vagrant does not create this folder.

It should probably not use a file to determine version, and use the vagrant api.

**Comment by tylerflint** [comment]
@suyashbansal Thanks for finding this. The help is greatly appreciated! 

@HLDahquan Thanks for your insight into this!

@dubcanada Again, thanks for your continued assistance on this and other issues. You're great!

Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. Nanobox no longer depends on Vagrant, and so this is no longer an issue. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
