### ISSUE TITLE
nanobox is in a suspended state disassociates vm from vagrant

### ISSUE THREAD

**Issue by sdomino** [nanobox-io/nanobox#14]
when nanobox is in a suspended state, running multiple (3) `nanobox dev`s nearly concurrently causes the '~/.nanobox/apps/odin/.vagrant/machines/odin/virtualbox' directory to get wiped, thus disassociating the vm from vagrant

**Comment by tylerflint** [comment]
It seems the underlying issue here is a bug within virtualbox. I believe @lyondhill has information regarding a known issue on the virtualbox bug list?
