### ISSUE TITLE
too many open files in system

### ISSUE THREAD

**Issue by JakeHenshall** [nanobox-io/nanobox#142]
Hi,

I just been playing around with nanobox,

but i get this error quite alot

INFO Unable to watch dir /Applications/MAMP/htdocs/kirki - too many open files in system

Im running Mac OSX El Capitan.

Is there anyway to solve this.

**Comment by dubcanada** [comment]
This is not a nanobox problem - see http://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by tylerflint** [comment]
@JakeHenshall Thanks for finding this. The help is greatly appreciated! 

Also special thanks to @dubcanada for your insight and help on this and many other open issues!

Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. The Nanobox filesystem watcher has been completely architected, and this should no longer be an issue. Essentially, if the native filesystem watcher fails (as shown above), Nanobox will revert to a custom polling solution. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
