### ISSUE TITLE
Using Nanobox

### ISSUE THREAD

**Issue by JakeHenshall** [nanobox-io/nanobox#143]
Hi,

I just have a few questions about using Nanobox:

1. How to I access the database it creates from using WordPress. (Where do i find it)
2. Do I put the Boxfile / Engine etc... in the theme folder or in the root of the entire WordPress installation (where wp-content is)
3. Can I put all of my WordPress websites in a Code Directory and run them from there.
4. Once i've developed my WordPress install, can i push it straight over to (Gitlab / Digital Ocean)?

Thanks Jake.

**Comment by sdomino** [comment]
1. If you run "nanobox info" it should give you connection credentials for your database and you can connect using another client (like sqlpro)
2. Put them at the root of your project
3. You can run "nanobox dev" from any project directory and it will then mount that directory into the VM.
4. You can outside of the Nanobox CLI just like you would normally. Very soon however, our production service will be available, with tools integrated right into the CLI for that. It will allow you to develop your app and deploy it directly to a host of your choice (https://nanobox.io/).
