### ISSUE TITLE
Tries to create folder in X:\

### ISSUE THREAD

**Issue by kurtextrem** [nanobox-io/nanobox#144]
The primary HDD is C:\, although my company has X:\ as well. Nanobox tries to create the folder at X:\.nanobox. Is there any way to change that?

**Comment by dubcanada** [comment]
It seems to use https://github.com/mitchellh/go-homedir/blob/master/homedir.go to determine home directory. Which seems to use environment variables. You should be able to set a `HOMEDRIVE` and `HOMEPATH` environment variable to change it to what ever you want.

See https://github.com/mitchellh/go-homedir/blob/master/homedir.go#L121

**Comment by kurtextrem** [comment]
Thank you, but I can't set that variable. I see if I can contact an IT Admin.

**Comment by tylerflint** [comment]
Thanks for finding this. The help is greatly appreciated! 

Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. Nanobox no longer depends on Vagrant, and so this is no longer an issue. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
