### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by dubcanada** [nanobox-io/nanobox#145]
Hello,

I have having a bunch of problems on Windows.

1. No matter what on the first run it fails, with an error `[util/server/mist/mist] client.Subscribe() failed - closed` but it does seem to work, running the command again causes it to continue/work.

2. I created a box successfully (once, I deleted the box once I had it created successfully and was not able to do so again) but it did not set anything in my host file and I was not able to determine the IP.

3. Destroy does not seem to delete a running VirtualBox. I have to manually stop it and then destroy it. Then I have to open up VirtualBox and delete it.

4. It can't seem to progress past `FETCH NODEJS` It just sits there, I've let it sit for 25 minutes and still nothing.

5. It says it is running, but it is not running. See - https://i.imgsafe.org/f8e7339.jpg `vagrant status` also says it is not running.

**Comment by tylerflint** [comment]
Thanks for finding this. The help is greatly appreciated! 

Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. Nanobox no longer depends on Vagrant, and so this is no longer an issue. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
