### ISSUE TITLE
nanobox update fails with 'text file busy' error

### ISSUE THREAD

**Issue by sdomino** [nanobox-io/nanobox#15]

**Comment by glinton** [comment]
Confirmed it is the `os.Create` [here](https://github.com/nanobox-io/nanobox/blob/master/commands/update.go#L92). In a separate test app, running on linux, attempting to os.Create() over the current file fails. Writing succeeds without issue on darwin systems.

**Comment by sdomino** [comment]
this is fixed in https://github.com/nanobox-io/nanobox/pull/22
