### ISSUE TITLE
404 page for /cloud

### ISSUE THREAD

**Issue by danielkalen** [nanobox-io/nanobox#150]
https://nanobox.io/cloud returns a 404 page

**Comment by danielkalen** [comment]
I noticed it's the link specified for the cloud menu item in this page https://engines.nanobox.io/

**Comment by tylerflint** [comment]
Hi @danielkalen. Thanks for the heads up! At this point we're right around the corner from releasing a completely re-designed version of the product. This release will introduce a modified development workflow and an integration into production cloud deployments (aws, digital ocean, etc). As such, a new website will be released. Once the new site is up, this particular issue will be addressed as the navigation will be completely new.

You're discovery is greatly appreciated. Also, I'm wondering if you'd be interested in reviewing the new release and site before it goes live?

**Comment by danielkalen** [comment]
Oh, of course! :)

I happen to also be a web, graphic, and UX designer and so far the version that's available at the moment is absolutely great in terms of design! Hope you're not getting rid of the dark theme :)

**Comment by tylerflint** [comment]
Sorry for the delay, It's finally here! The new site didn't drop the dark theme altogether, but it's now a lesser part of the theme. I'd be curious to get your thoughts before we start to turn up the marketing. Thanks!
