### ISSUE TITLE
Feature: RethinkDB

### ISSUE THREAD

**Issue by kalicki** [nanobox-io/nanobox#163]
Ideia: Support noSQL with RethinkDB?!

**Comment by tylerflint** [comment]
@kalicki Thanks for submitting this! This is already underway, and being tracked via another project. I'll go ahead and close this issue here. RethinkDB should be available in the coming weeks. Thanks!

**Comment by winuxue** [comment]
status?

**Comment by notxarb** [comment]
@winuxue Please check out these repos:
https://github.com/nanobox-io/nanobox-hooks-rethinkdb
https://github.com/nanobox-io/nanobox-docker-rethinkdb
