### ISSUE TITLE
Add output suggesting the use of `-p` flag on EADDRINUSE

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#183]
`nanobox help tunnel` does provide the flag required to avoid the error:  
>`-p, --port string       local port to start listening on`  

Perhaps it could be added to the error output:

>```
$ nanobox tunnel data.db
Error   : address already in use [specify new local port `-p <integer>`]
Context : failed to connect to remote tunnel session -> failed to setup tcp listener -> listen tcp4 :5432 -> bind
```

**Comment by lyondhill** [comment]
I think it might be something we would like to catch early. and warn about.
