### ISSUE TITLE
Show ip information after running a `nanobox sim start`

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#185]
Similar to how `nanobox sim deploy` gives address information, it would be useful for start to give similar/same output.

> `nanobox sim deploy` referenced output
> 
> ```
> --------------------------------------------------------------------------------
> + Your app is running in simulated production environment
> + Access your app at >> 192.168.99.54
> --------------------------------------------------------------------------------
> ```

**Workaround:** `nanobox sim info` after a successful `nanobox sim start` will return the needed info

> `nanobox sim info` referenced output
> 
> ```
> -------------------------------------
> pulse (sim)              Status: up  
> -------------------------------------
> 
> Router  IP: 192.168.99.54
> ...
> ```

**Comment by lyondhill** [comment]
@Tolmark12 @tylerflint maybe you guys should weigh in on this
