### ISSUE TITLE
Boxfile `port: 3000` does not equal `port: 3000:3000` like the docs say

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#21]
According to (the docs)[https://docs.nanobox.io/boxfile/code-services/tcp/#ports], nanobox interprets a single port number (3000) as that same port for the source and destination (3000:3000), but nanobox fails to accept traffic on that port, even though the app is listening
```
tcp1:
  ...
  ports:
    - 3000
```
$ curl sample-app.dev:3000
curl: (7) Failed to connect to sample-go.dev port 3000: Connection refused

**Comment by sdomino** [comment]
This issue was moved to nanobox-io/nanobox-server#10
