### ISSUE TITLE
Nanobox login fails on Windows 10 with Git Bash

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#225]
Trying to login on Windows 10 and Git Bash fails:

```
$ nanobox login
Username: mbrodala

Error   : Das Handle ist ungültig.
Context : failed to read password

Enter to continue:
```

(The Error means "the handle is invalid".)

It works with the default `cmd.exe` though:

```
...>nanobox login
Username: mbrodala
Password:
√ You've successfully logged in
```

**Comment by lyondhill** [comment]
git bash provides bash in windows. the problem is the way that bash handles terminals and the way the terminal switching works.

I will put in a warning to make it so it is clear that nanobox is clear about why its failing on gitbash
