### ISSUE TITLE
Cannot access dashboard with Chromium

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#238]
If I try to open the dashboard with Chromium, I am redirected to the following error page:

https://dashboard.nanobox.io/426

This should be fixed since Chromium is essentially the same as Chrome minus a few non-free pieces.

**Comment by glinton** [comment]
@mbrodala What version of Chromium are you running and do you have any extensions that may interfere?

**Comment by lyondhill** [comment]
we are using a project called Modernizr to determin if your browser has the required features. The list of features we currently require are here https://modernizr.com/download/?borderradius-boxshadow-boxsizing-canvas-checked-cookies-cors-cssanimations-csspointerevents-csspseudoanimations-csspseudotransitions-csstransforms-csstransitions-cssvalid-displaytable-ellipsis-es5-eventlistener-flexbox-fontface-formvalidation-generatedcontent-hashchange-hiddenscroll-history-inlinesvg-input-inputtypes-json-lastchild-localstorage-mediaqueries-nthchild-opacity-placeholder-queryselector-requestanimationframe-rgba-sessionstorage-siblinggeneral-svg-svgasimg-svgclippaths-svgfilters-target-unicode-userselect-websockets-setclasses

**Comment by mbrodala** [comment]
Re-posted from Slack:

> Version 53.0.2785.143 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

Console says:

```
Modernizr_hiddenscroll: false
Modernizr_csspseudoanimations: false
Modernizr_csspseudotransitions: false
Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
Failed to load resource: the server responded with a status of 426 (Upgrade Required)
```

**Comment by lyondhill** [comment]
im using `53.0.2785.143 (Developer Build) Built on Ubuntu` and its working for me. one of your chrome extensions may be getting in the way.

**Comment by mbrodala** [comment]
Just tried Incognito mode where no extension is enabled but still no luck.

**Comment by mbrodala** [comment]
I was able to fix the `localStorage` security error by adding an exception for `static.olark.com`. (see [background](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document))

**Comment by lyondhill** [comment]
This issue was moved to nanobox-io/nanobox-dashboard-issues#5
