### ISSUE TITLE
Not all Apache modules loaded

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#239]
[The documentation](http://guides.nanobox.io/php/apache-settings/#apache_modules) currently says:

> Specify which Apache modules to enable or disable. View the [full list of available Apache Modules](https://github.com/nanobox-io/nanobox-engine-php/blob/master/doc/apache-modules.md). By default, all modules are enabled.

However, this is not the case:

```
$ apachectl -t -D DUMP_MODULES
Loaded Modules:
 core_module (static)
 mpm_prefork_module (static)
 http_module (static)
 so_module (static)
 dir_module (shared)
 env_module (shared)
 expires_module (shared)
 log_config_module (shared)
 mime_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 deflate_module (shared)
 actions_module (shared)
 alias_module (shared)
 fastcgi_module (shared)
Syntax OK
```

I just stumbled over this due to an error and the following log message:

> [Thu Nov 03 14:59:40 2016] [alert] [client 192.168.99.1] /app/web/.htaccess: Invalid command 'Order', perhaps misspelled or defined by a module not included in the server configuration

(Missing `mod_authz_host`.)

**Comment by mbrodala** [comment]
Notice for passersby: Add your modules like this and re-run the app:

```yaml
code.build:
  config:
    apache_modules:
      - authz_host
```

**Comment by notxarb** [comment]
We refactored that, and didn't update the docs. We decided it probably shouldn't load all of the extensions as many of them might not be commonly used. We can add that into the list of default extensions.

**Comment by mbrodala** [comment]
I'm not sure about which modules Apache loads by default. With classic solutions I'd tend to not load any module by default and make everything explicit instead but since NB allows for exactly the same environment in dev and production, this doesn't matter.

**Comment by notxarb** [comment]
I have a pull request to the guides to update the section about the apache modules. https://github.com/nanobox-io/nanobox-guides/pull/8

**Comment by mbrodala** [comment]
Thanks, that helps. :-)
