### ISSUE TITLE
Randomly "connection reset by peer"

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#252]
From time to time pulling images seems to fail:

```
+ (nanobox dev deploy) :
  + Preparing environment :
    + Mounting codebase :
  + Syncing data components :
    + Removing old :
      + Skipping (up-to-date) :
    + Launching new :
      + data.mysql :
        + Pulling nanobox/mysql:5.6 image :

Error   : connection reset by peer
Context : failed to sync components -> failed to provision components -> failed to setup component (data.mysql) -> failed to pull docker image (nanobox/mysql:5.6) -> Error response from daemon -> Get https://registry-1.docker.io/v2/nanobox/mysql/manifests/5.6 -> read tcp 10.0.2.15:57958->52.206.180.136:443 -> read

Enter to continue:
```

(Output by `nanobox dev run --debug --trace`)

Our local network connection is fast and stable but I cannot imagine the Docker registry to have hiccups either, so I'm not sure what the issue could be.

**Comment by tylerflint** [comment]
@lyondhill I wonder if for this particular task, we should consider retrying a couple of times

**Comment by lyondhill** [comment]
I like that. I will write up a prototype pull request.

**Comment by mbrodala** [comment]
I'll let you know if I stumble upon this issue again. Thanks for fixing. :-)
