### ISSUE TITLE
Cannot use cursor keys on Windows

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#268]
I cannot use cursor keys to edit the current CLI input on `nanobox run`. I can neither move in the current input with left/right nor recall previous/following commands with up/down. It doesn't even work in `vim`.

This happens both with `cmd.exe` as well as PowerShell.

**Comment by lyondhill** [comment]
so I have been working on this problem for a little while and pushed a fix on wednesday that solved the bash history problem but not the vim problem https://github.com/nanobox-io/nanobox/pull/266 I will be working on solving the rest of the cursor problem this week.

**Comment by mbrodala** [comment]
Cursor movement within seems to work now but the rendering when scrolling down this way is weird (it simply overwrites the last line and collects garbage.)

**Comment by mbrodala** [comment]
This still does not work, even with cmder, the left and up cursor don't do anything ATM.
