### ISSUE TITLE
can't create symlinks on windows

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#269]
It appears that creating symlinks within nanobox when running on windows fails. The issue appears to be quite in depth.

Details forthcoming...

**Comment by mbrodala** [comment]
More details from my side: with `mount-type: netfs` in `~/.nanobox/config.yml` CIFS (MS implementation of SMB) is used to mount the code from the host system as `/app` within the main container.

According to some research the CIFS mount option [`mfsymlinks`](https://wiki.samba.org/index.php/UNIX_Extensions#Minshall.2BFrench_symlinks) could help achieving the desired behavior. With this option symlinks are created as files with specific content on the Windows host system but usable as regular symlinks on the CIFS Linux client.

**Comment by mbrodala** [comment]
AFAIS this works in [Docker for Windows since version 1.12.1](https://github.com/docker/docker.github.io/blob/af1a2bf3400ef39a804c53fb541f9d965af9bd98/docker-for-windows/release-notes.md#docker-for-windows-1121-2016-09-16-stable):

> Added `mfsymlinks` SMB option to support symlinks on bind mounted folder

From examples I can see that `vers=3.02` is used for the mount whereas `vers=1.0` is currently used in Nanobox.

**Comment by tylerflint** [comment]
Adding research provided by @danhunsaker (much thanks!):

Article explaining what is required to allow windows user to make actual links:
https://mikemstech.blogspot.com/2012/10/windows-symbolic-links-and-file-sharing.html

Comment from @danhunsaker from slack:
"Distilling from the above link, the user needs permission to create symlinks, but the security model still prevents creating/following symlinks on shares ("remote" symlinks) - `fsutil behavior set SymlinkEvaluation R2R:1` is also required, though I expect a GPO is modified that could be referenced as well.

In the case of the symlink being created by @mbrodala's framework, `R2L:1` may also be required, as the symlink is being created on a CIFS share (`/app`, which is considered "remote") to point to a `cache_dir` (`/dev/sda1`, which is considered "local")."

**Comment by tylerflint** [comment]
As I see it, we have 2 options to pursue here:

1 - Figure out how to make actual links that windows will respect.
2 - Add a translation layer (like mfsymlinks).

While option 2 is probably more likely to find a path of success, there are a couple of heavy downsides:

- We will need to figure out how to apply the solution to both CIFS and virtualbox native.
- The mfsymlinks option creates a file with metadata that the mount will use to manipulate the filesystem requests. Once the mount is gone (when the app is running live on production) that file will not be interpreted as a linux symlink. Thus, if this option is pursued, it will need to be accompanied by a process during the deploy that will convert these files into actual symlinks that linux will respect.
- The file created will likely cause problems with other developers running the app on mac or linux.

I think if the translation layer were the chosen path, some serious thought will need to go into how to convert these links into real links when not on windows. I can imagine the conversion would create some frustrating git commit artifacts as the project moves between developers across multiple environments.

Given this, it seems that we should really try to figure out how to get windows to respect actual links first. If this is not possible (I wouldn't be surprised) then we need to really think about how to properly integrate a windows link translation layer.

**Comment by tylerflint** [comment]
Sadly, it looks like this is something that will fall outside of what nanobox can provide. Essentially, Windows and Unix have completely separate implementations for creating symlinks. The problem here is that if a symlink is created within the source code on Mac or Linux, then a Windows developer were to pull the same source code which includes that link, Windows would not treat it as a symlink. The inverse is also true. Additional information can be found here: http://unix.stackexchange.com/questions/63172/does-windows-recognize-linuxs-symbolic-links

The core of the issue here has less to do with whether nanobox can get windows to support links (we can), and has everything to do with whether a symlink in the app source would even work at all. Yes, a symlink created on Linux would work on Linux and from Windows would work on Windows etc. However, that link will only work on the environment where it was created.

Ultimately, our conclusion here is that symlinks within the source code are simply not safe at all. Given this reality, it is our recommendation that alternative methods should be used rather than a practice of using symlink within the source code directly.

Generally, there are a couple of alternatives to using symlinks:

- Files can be shimmed instead of linked directly. This simply means that rather than linking a file directly, a destination file should be created that will include, require, or simply call the source file directly. Additionally, files can simply be copied into the proper place.
- Directories do not need to be linked, instead, references to the directory location can be adjusted to the real path.

Some implementations will certainly be more involved than others. Please feel free to join us on slack for assistance.

**Comment by mbrodala** [comment]
For our specific case ([TYPO3](https://packagist.org/packages/typo3/cms) + [TYPO3 Composer installers](https://packagist.org/packages/typo3/cms-composer-installers)) work is in progress for newer versions but we are not there yet. Currently we have the following mandatory symlinks:

- `<web-dir>/index.php` (frontend)
- `<web-dir>/typo3/` (backend)

While `index.php` could be achieved with a dummy file requiring the real one, the backend access cannot be replaced ATM.

Since this means that TYPO3 is currently not usable within Nanobox on Windows hosts, I'd really like to at least have a workaround or optional flag to e.g. enable `mfsymlinks`.

**Comment by mbrodala** [comment]
Works like a charm after setting `netfs_mount_opts: mfsymlinks` in `~/.nanobox/config.yml` and `nanobox run` after a fresh system start (or `nanobox stop` before).
