### ISSUE TITLE
Build required after 'reload'

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#27]
After a 'nanobox reload', the containers are restarted and docker assigns new IP addresses. This is only an issue because the previous build set environment variables to values of the previous IP addresses.

The solution is pretty straight forward: Whenever a 'nanobox reload' is run, we need to set a flag in the nanoconfig file to be used on subsequent "dev" or "run" commands that will force a build.

**Comment by sdomino** [comment]
implemented here: https://github.com/nanobox-io/nanobox/commit/9a77a4736c9b64468a501912ca5b5c5ba9d2faa2
