### ISSUE TITLE
Set VM expectation on first run

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#271]
First time using "nanobox run" gives the impression that nanobox creates a VM for every app. We need to create a message and set the expectation the first time nanobox creates a VM.

**Comment by lyondhill** [comment]
@tylerflint  @Tolmark12  any updates.. I need to get the message and where it should be placed

**Comment by tylerflint** [comment]
--------------------------------------------------------------------------------
+ HEADS UP:
+ Nanobox will run a single VM transparently within VirtualBox.
+ All apps and containers will be launched within the same VM.
--------------------------------------------------------------------------------
