### ISSUE TITLE
Catch/display local mails

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#274]
With our current Vagrant setup we automatically install and run [MailHog](https://github.com/mailhog/MailHog) locally and instruct the system to use it as `sendmail` binary. This way outgoing mails are caught by MailHog and can be inspected.

It would be great if Nanobox had something similar to catch outgoing mails when running locally. I could imagine this as another data component or similar but I'm not sure how to skip a component in production which would be essential here.

**Comment by tylerflint** [comment]
This issue was moved to nanobox-io/nanobox-engine-php#32
