### ISSUE TITLE
Proxy for LAN access

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#275]
Currently, nanobox builds a virtual network for the local machine only. If running an app with nanobox via `nanobox run`, the app is only accessible to the local host directly. This is especially limiting to mobile developers who want to access their dev api from an actual mobile device.

Attempting to bridge nanobox to the LAN network would be cumbersome, as each app gets multiple unique IP addresses. This would require adding an interface into virtualbox for every app. Not to mention a LAN that assigns static IP addresses would be a mess.

A simple solution would be to implement a dumb proxy as an opt-in feature to `nanobox run`. Essentially, if the proxy was enabled for the app, a `nanobox run` would spawn a dumb proxy in a goroutine for the duration of the session. The dumb proxy would just bind to a local 0.0.0.0 interface at a certain port, and forward packets to the local app IP at a destination port. 

The configuration still needs to be thought through, but conceptually might look something like this:

```yaml
run.config:
  proxy: tcp:8080:80
```

**Comment by lyondhill** [comment]
will this be solved with the new vpn solution?

**Comment by tylerflint** [comment]
Unfortunately, no. The vpn will only bridge the local network with the virtual network. It’s won’t bridge the virtual network with the LAN network.

**Comment by tylerflint** [comment]
ngrok was brought up in the nanobox slack channel over the weekend. Ngrok solves this problem already in addition to providing public tunnels: https://ngrok.com/
