### ISSUE TITLE
Build triggers

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#276]
Currently, nanobox will run the build-runtime phase conditionally during a `nanobox run` when the boxfile.yml changes. Ideally, nanobox would also trigger the build-runtime when dependency configuration has changed (as fetching app dependencies happens during this phase). The problem with this is that nanobox is language/framework agnostic and doesn't know which files to look for changes.

The solution would be to add a `build_triggers` attribute into the `run.config` section of the boxfile.yml which will allow an engine (or a user) to specify which files to checksum and trigger a build-runtime. On `nanobox run`, nanobox will then check those files to see if they've changed since the last `nanobox run` and if they have, it will rebuild the runtime environment

**Comment by notxarb** [comment]
This is linked to https://github.com/nanobox-io/nanobox-docker-build/pull/98
