### ISSUE TITLE
Support HTTPS (SSL/TLS)

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#278]
Right now an application needs to take measures when running within Nanobox (local/dry-run) if HTTPS should be used/enforced since no HTTPS was configured.

It would be useful to have a usable HTTPS setup, either with a real certificate or at least with a self-signed one which can be temporarily accepted in browsers.

**Comment by kristoftorfs** [comment]
Is there any progress on this? I think simply allowing a Let's Encrypt certificate to be installed would be sufficient for 99% of people.

**Comment by danhunsaker** [comment]
It's made it to the roadmap, so I'd upvote it there.

**Comment by hl** [comment]
I'm trying a different approach but no dice.

https://github.com/hl/nanobox-phoenix/blob/master/Caddyfile

Start with 
```
$ nanobox run ./caddy
```

**Comment by danhunsaker** [comment]
The HTTPS layer needs to sit outside your app's web container(s), since that's how things will operate in production. I'm publishing an article, just as soon as I work out this Windows batch script, on a workaround you can until this feature is implemented natively.
