### ISSUE TITLE
NFS support for shared folders

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#28]
After a series of benchmarks, it is apparent that nfs is a much more efficient option for nanobox. There are a couple of caveats in using nfs with busybox (boot2docker) so the Vagrant configuration is a bit more involved than a simple `type: 'nfs'` option. Additionally, we can't use nfs on windows. Lastly, we should allow users to revert back to the default virtualbox adapter in the .nanofile if so desired.

Here is what the vagrant nfs configuration should look like:

```ruby
nanobox.vm.synced_folder "/Users/tylerflint/Work/nanobox/odin", "/vagrant/code/odin",
  type: "nfs",
  mount_options: ['nfsvers=3', 'proto=tcp']
```

**Comment by sdomino** [comment]
implemented here: https://github.com/nanobox-io/nanobox/commit/9a77a4736c9b64468a501912ca5b5c5ba9d2faa2
