### ISSUE TITLE
Spaces in ssh key file names prevent them from being copied into the VM

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox#282]
This was found by @danhunsaker which helped troubleshoot a problem @atourino ran into:

https://github.com/nanobox-io/nanobox/blob/master/generators/hooks/build/user.go#L15

> Not sure the best way to make Ruby properly quote shell commands inside the VM, but that'll be the actual fix

**Comment by lyondhill** [comment]
This issue was moved to nanopack/hookit#10
