### ISSUE TITLE
provide a simpler way to expand the vbox disk

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#284]
Once the nanobox (bootdocker) image runs out of disk, expanding the disk is a very complicated process. I've created a gist to outline what needs to be done: https://gist.github.com/tylerflint/a971b891e88645a5ca26267c0a9eb588

We need to figure out how to script the process (some parts of that gist are manual) and then integrate into nanobox with some command to trigger the process.

**Comment by lyondhill** [comment]
https://github.com/nanobox-io/nanobox/issues/284 
extending the disk is hard. but recreating the vm with a larger disk is a quick capture.
I say we solve that issue and close this one. and if we still have interest in resizing we can reopen this

**Comment by danhunsaker** [comment]
My 2¢: Recreate VM, Migrate Data, Destroy Old VM.  Seems best, to me, to stick with existing approaches to the same problems.

**Comment by lyondhill** [comment]
If we get more interest in this now that we can create with different sizes we will re open this issue
