### ISSUE TITLE
Adding an "unitialized" app as a remote

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox#289]
**Use Case:** A user creates an app in their dashboard and immediately tries to add it as a remote. The CLI returns a message that you do not have access to this app because the app has not been fully initialized yet. There user thinks something is wrong, because there's no message about the app not being ready.

**Suggestion:** Somehow make the response in the CLI more informative: "This app is still initializing", "This app isn't ready yet", etc.

**Comment by lyondhill** [comment]
this would be a good thing to add to odin. 
once we have solved https://github.com/nanobox-io/nanobox/issues/287 the messages from odin will come through

**Comment by jedgalbraith** [comment]
The fixes to Odin have been deployed. Now users can add remote links to apps before they're fully 'active'. Then if they attempt to deploy or perform an action before the app has the necessary platform services, Odin will return a 404 for that platform service. Previously it was returning a 200 with a `nil` body.

**Comment by lyondhill** [comment]
awesome. I will close the issue with my pull request.
