### ISSUE TITLE
migration for native

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox#297]
add a migration check for native and implode the environment iit needs to be

**Comment by lyondhill** [comment]
@tylerflint @Tolmark12 I need a message to put in here

**Comment by tylerflint** [comment]
Great news! Nanobox can now optionally run directly on top of Docker. This change constitutes a major architectural refactor as well as data re-structure. To use this version we need to purge all of your current apps. Fortunately, nanobox will re-build them for you the next time you use "nanobox run".

[Enter to Continue]
