### ISSUE TITLE
Custom logs not watched on local/dev

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#299]
Here's an excerpt from my `boxfile.yml`:

```
# ...
web.site:
  # ...

  log_watch:
    apache[access]: /data/var/log/apache/access.log
    apache[error]: /data/var/log/apache/error.log
    php[error]: /data/var/log/php/php_error.log
    php[fpm]: /data/var/log/php/php_fpm.log
    typo3[typo3]: var/log/typo3.log
    # ...
```

However, only the `apache` and `php` logs are watched and outputted on `nanbox run php-server`, the `typo3` log is ignored. Is there anything I missed?

**Comment by mbrodala** [comment]
I can see the following after `nanobox run`:

```
/app $ ps aux | grep tail
gonano     136  0.0  0.0   6044   716 ?        S+   09:36   0:00 tail -f -n0 /data/var/log/php/php_error.log /data/var/log/php/php_fpm.log /data/var/log/apache/access.log /data/var/log/apache/error.log
```

So it looks like my custom log was indeed ignored.

**Comment by danhunsaker** [comment]
This is actually because the web instance isn't being created in the first place - dev mode doesn't spin up separate containers for webs and workers, instead spinning up one container for each app's console.  So any settings in the `web.*` or `worker.*` sections aren't applied in development mode; they'll only kick in when deployed to dry-run or production.

**Comment by mbrodala** [comment]
I guess this makes sense; even `php-server` is invoked manually and no `network_dirs` are set up (not neccessary).

But still I can see log output on `nanobox run php-server`; would it be possible to include custom logs here? Just as minor feature request. Of course I can open/tail the app logs on my host system if not. ;-)

**Comment by danhunsaker** [comment]
I'd enjoy that as well.  I'll have a peek at the engine repo and see if I can tweak the script any.  The big trouble will be parsing the Boxfile - that isn't generally done outside the build/compile phases.

**Comment by danhunsaker** [comment]
Ah.  Well.  `php-server` is generated from a template.  While the Boxfile is accessible.  That shouldn't be too tricky to work with to give this additional functionality, though I'll probably have to look at it tomorrow or so.

**Comment by lyondhill** [comment]
This issue was moved to nanobox-io/nanobox-engine-php#37

**Comment by mbrodala** [comment]
@lyondhill It seems like this also affects production. I can not see any of my custom logs in the "Logs" section within the Nanobox UI. If I `tail -f` one of the log files within `nanobox console web.site`, I can clearly see new log messages though.

Is this unrelated?

**Comment by lyondhill** [comment]
sounds like it could be a seperate issue. this should be noted on nanobox-io/nanobox-engine-php#37 i just moved this issue to that location

**Comment by mbrodala** [comment]
Thanks, I've created nanobox-io/nanobox-engine-php#39 for this.
