### ISSUE TITLE
dhcp service won't die!

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#30]
It appears that the dhcp service is still alive and well. This presents a significant challenge as the dhcp service will periodically release the IP and request a new one. Oddly, we provide a static IP so it's a bit perplexing as to why the dhcp service is running in the first place. The dhcp service appears to be part of the boot2docker box.

Several provisions are are in place as an attempt to kill the dhcp service on boot: https://github.com/nanobox-io/nanobox/blob/master/util/vagrant/init.go#L148-L164

It would appear that the dhcp service is hardier than initially expected.

@glinton Perhaps we could look into disabling the service altogether in the boot2docker box, and not rely on Vagrant provisioning attempts?

**Comment by sdomino** [comment]
The update lines are: https://github.com/nanobox-io/nanobox/blob/master/util/vagrant/init.go#L168-L184

**Comment by glinton** [comment]
Have you tried adding 'auto_config: false' to the options specified [in this line](https://github.com/nanobox-io/nanobox/blob/master/util/vagrant/init.go#L61)

**Comment by sdomino** [comment]
@glinton will adding that line possibly remove the need to have our shell script killing the server?
