### ISSUE TITLE
Read username/password from environment variables

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#300]
In addition to interactively asking for username/password on `nanobox login` (and consequently on `nanobox remote add ...`) Nanobox should be able to read credentials from predefined environment variables. I'd suggest:

- `NANOBOX_USERNAME`
- `NANOBOX_PASSWORD`
- `NANOBOX_ENDPOINT`

This is essential for workflows where e.g. deployments should be triggered from a CI server after performing all necessary checks and tests. Usually data like credentials can be stored as encrypted environment variables here which are decrypted and provided during build.

**Comment by lyondhill** [comment]
great suggestion. and it should be a quick capture.

**Comment by mbrodala** [comment]
Thanks a lot for adding this. :-)

**Comment by lyondhill** [comment]
no problem. I actually was able to take it just one step further. if you have the env var's set you shouldnt need to run the 'login' command at all.

**Comment by mbrodala** [comment]
@lyondhill Yeah, saw that and this matches my planned CI workflow perfectly. :-)
