### ISSUE TITLE
Add support for Git Bash on Windows

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#303]
Since both `cmd.exe` as well as Powershell are a huge PITA to use on Windows, Nanobox should support the Git Bash. There are a few issues (e.g. #225) which prevent this ATM which need to be fixed first.

**Comment by lyondhill** [comment]
cmd and powershell do have there shortcomings. Have you tried cmder? not to say we wont eventually add support for git bash. but cmder has been better then git bash for windows IMO.

**Comment by mbrodala** [comment]
So *that's* the terminal I have seen in the screenshots floating around. I'll give it a try. :-)

**Comment by loganpowell** [comment]
👍 for Git Bash

**Comment by lyondhill** [comment]
We currently dont suppurt git bash but we will be doing a revamp to the supported terminals on windows when WSL comes out of beta and that is probably when we will add support for gitbash

**Comment by mbrodala** [comment]
For people reading this: WSL = [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/about).

**Comment by danhunsaker** [comment]
Lyon is no longer with Nanobox, but the issues with Git Bash are on the Docker level, rather than the Nanobox level. Until Git Bash and Docker learn to play nice, Nanobox can't support Git Bash. 🙁

**Comment by mbrodala** [comment]
I just had a look and discovered this article: [Docker for Windows: Interactive Sessions in MinTTY Git Bash](http://willi.am/blog/2016/08/08/docker-for-windows-interactive-sessions-in-mintty-git-bash/).

I did as instructed and reinstalled Git Bash using `cmd.exe` but Nanobox still won't allow me to use it since it simply checks whether the shell is bash (6c299001200d7237c6fcb3f6021f2ed4ba3a0d14).

Can you change this check to detect whether `cmd.exe` is used in Git Bash? I just had a look at the `env` output of both variants and this is what I see:

- MinTTY uses `TERM=xterm`
- `cmd.exe` uses `TERM=cygwin`

Maybe the mentioned check can be changed to take this into account and allow Git Bash with `cmd.exe` as console window?
