### ISSUE TITLE
over reasonable disk space usage

### ISSUE THREAD

**Issue by vinyll** [nanobox-io/nanobox#306]
I'm trying a basic app with Django and the Nanobox is taking 3.8Gb of disk space.
When your disk is a 128gb ssd drive and this nanobox is one single basic project among others, that's consequent.

I see that nanobox is strongly based on Docker.
Maybe could you consider using Alpine images?

**Comment by lyondhill** [comment]
nanobox creates an isolated environment for every application. What is happening is you are installing a very small image for virtual box (rough 38m) then we pull down minimal docker images. Then we install the language and all dependencies that your app needs in an isolated environment. I am guessing the vast majorty of your 3.8Gb of usage is coming from the dependencies.

**Comment by tylerflint** [comment]
That said, we're always looking to optimize; It's an ongoing effort. Would you mind providing where you're seeing the 3.8Gb of usage?

Thanks

**Comment by vinyll** [comment]
Well, the same project is 2.9Mb and all its dependencies are 50Mb when installed on my system.
The project is https://github.com/CommonsDev/sso.
Here attached is a screenshot of that nanobox. I may have done something wrong to reach that amount of disk space…
![screen shot 2016-12-19 at 2 43 43 pm](https://cloud.githubusercontent.com/assets/145172/21328449/9b3c1ca0-c5f9-11e6-85e0-77cd30daa14d.png)

**Comment by tylerflint** [comment]
I don't think you've done anything wrong. Nanobox is an ambitious project and we haven't yet been able to focus on optimizing for disk efficiency. You're totally fine. 

However, since you're the first to actually report the issue, I'm hoping you'll be willing to investigate where we can do better ;)

**Comment by vinyll** [comment]
I try to delete an reinstall; I'll have a deeper look to check why it's requiring such a large amount.
I had similar issues with Docker until I used only Alpine based images.

**Comment by tylerflint** [comment]
Also, the "dependencies" that @lyondhill is referring to are the environment dependencies: binaries, libraries, build tools, etc. The actual application and app dependencies are likely very small as you've mentioned.

As a point of reference, the Xcode build tools for mac install at ~3gb as a minimum. The build image (nanobox/build) will be at least 1GB unpacked simply due to the build tools required for compiling and linking.

**Comment by tylerflint** [comment]
@notxarb When you get a moment, can you provide some instructions for isolating disk usage within the VM?

**Comment by vinyll** [comment]
I've deleted the folder _machine/nanobox_ and rerun `nanobox start` and `nanobox run` in that same folder.
The disk usage of _disk.vmdk_ has now been reduced to 10Mb, which is very fine.
I'm not sure then why I had these 3.8Gb for that image.
Notice I had asked to build with Docker on my first launch of nanobox before I was told it was not ready yet. I then moved to the suggested VM.
Maybe is it linked?

**Comment by tylerflint** [comment]
Hey @vinyll, could you check the current usage now?

**Comment by glinton** [comment]
I just ran out of space on the disk the nanobox vm is using and I happened to check its disk usage:
![image](https://cloud.githubusercontent.com/assets/2653109/23274535/52c3e336-f9c0-11e6-92fe-57eefbaaecea.png)

I did have 5 apps, but it seems like old images may be part of the issue as all those apps are `down`:
```
docker@nanobox:~$ docker images
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
nanobox/build        latest              54e899273e41        6 days ago          587.4 MB
nanobox/build        bugfix_nosupdate    b63a08c1c881        2 weeks ago         587.4 MB
nanobox/mysql        latest              f9401b450a36        2 weeks ago         737.5 MB
nanobox/code         latest              3f92f5e4a03e        2 weeks ago         351.3 MB
nanobox/redis        latest              471f67205b3b        2 weeks ago         416 MB
nanobox/unfs         latest              3c0e9e80e675        2 weeks ago         362.7 MB
nanobox/logvac       latest              049dd48d9e0f        2 weeks ago         332 MB
nanobox/unfs         <none>              a328aedc80b1        3 weeks ago         362.5 MB
nanobox/redis        <none>              68b12cbc0a2e        3 weeks ago         415.8 MB
nanobox/mysql        <none>              a1ca198136cf        3 weeks ago         737.5 MB
nanobox/portal       latest              0493e06e34c9        3 weeks ago         387.6 MB
nanobox/mist         latest              11487fac4910        3 weeks ago         331.9 MB
nanobox/hoarder      latest              f6648c7ffcb8        3 weeks ago         344.3 MB
nanobox/code         <none>              df88fc0b61e9        3 weeks ago         351.3 MB
nanobox/build        <none>              3f1edc7f5ecc        6 weeks ago         723.7 MB
nanobox/postgresql   <none>              f7489edbac52        9 weeks ago         690.3 MB
nanobox/bridge       latest              b07bebe96c90        10 weeks ago        456.4 MB
```

**Comment by lyondhill** [comment]
i should be releasing 2.0.3 today.
