### ISSUE TITLE
App not accessible after scaling up

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#309]
I just scaled up my app on DO from the $5 to the $10 droplet via Nanobox' dashboard and now the app is not accessible anymore.

I currently get `HTTP/1.1 502 Bad Gateway` instead.

Neither container/platform health nor logs give an idea of the error.

**Comment by lyondhill** [comment]
This issue was moved to nanobox-io/nanobox-dashboard-issues#6
