### ISSUE TITLE
Plan payload doesn't get generated properly when complex config dataset is in the boxfile.

### ISSUE THREAD

**Issue by notxarb** [nanobox-io/nanobox#311]
Having some logging in to show why it failed to generate the payload would be helpful in debugging the issue.

**Comment by notxarb** [comment]
Here is a gist with a working and not working boxfile.
https://gist.github.com/notxarb/ec81267178700467d340917abef2cc26

**Comment by lyondhill** [comment]
if there is a map[string]interface{}{"string": map[interface{}]interface{}{"substring":whatever}} json cannot marshel the sub map
