### ISSUE TITLE
SSH key with Passphase breaks subsequent deployment

### ISSUE THREAD

**Issue by silentworks** [nanobox-io/nanobox#312]
With my application, the first deployment worked without any issues, but when I tried subsequent deployments they failed at `Extracting app from previous deploy...`. This is due to the default `id_rsa` ssh key having a passphase on it, once the passphase was removed deployments were back to normal.

**Comment by danhunsaker** [comment]
A suggestion for something that could be added (to any place that actually accepts such a key as input):

> Because Nanobox is largely automated, the SSH key you provide here must not have a passphrase.  Nanobox won't have any way to provide this passphrase, so many operations will fail.

**Comment by tylerflint** [comment]
Thanks for the input guys, a solution has been determined, and progress can be followed here: https://github.com/nanobox-io/nanobox/issues/328
