### ISSUE TITLE
Missing log file results in narc missing logs

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#313]
Narc starts up configured to watch `/var/log/gonano/node/current`which doesn't exist until narc has stopped watching it for several seconds.

In order to solve this, touch/create the files configured in narc before starting narc.

This results in a bad user experience, causing them to question whether or not their app is working.

>Log in to ensure app is running:
>```sh
>$ cat /var/log/gonano/node/current 
>2016-12-29T19:27:27.52168 Connecting....... Success!
>2016-12-29T19:27:28.55998 Authenticating... Success!
>2016-12-29T19:27:28.90682 Connected!

>Verify Narc started up first
>```sh
>$ tail /var/log/narc.log 
># narc starting up
>[120] 29 Dec 19:27:24.889 # opening file /var/log/gonano/node/current
>[120] 29 Dec 19:27:24.889 # server resolving: 192.168.0.2
>[120] 29 Dec 19:27:24.889 # Narc started, version 0.0.1
>[120] 29 Dec 19:27:24.889 # Waiting for events on 1 files
>
># started up, failed to open app log file, waiting 5 seconds to retry
>[120] 29 Dec 19:27:24.891 # Error opening /var/log/gonano/node/current (1/12): ENOENT
>
>[120] 29 Dec 19:27:24.891 # server resolved: '192.168.0.2' to 192.168.0.2:514
>
># finally opened the file after the logs have been logged
>[120] 29 Dec 19:27:29.891 # opening file /var/log/gonano/node/current
>[120] 29 Dec 19:27:29.891 # File opened: /var/log/gonano/node/current

**Comment by glinton** [comment]
I think applies to a hook/engine repo, but not sure which one[s]

**Comment by notxarb** [comment]
This should apply to hook repos, not engine ones. The code hooks should be creating the log files already. I think the data services probably need this.

**Comment by lyondhill** [comment]
This issue was moved to nanobox-io/nanobox-docker-build#108
