### ISSUE TITLE
offline support

### ISSUE THREAD

**Issue by philipgiuliani** [nanobox-io/nanobox#320]
It seems that nanobox is not capable of working offline at the moment.

**Expected behaviour:**
When the boxfile.yml has no changes and I run `nanobox run` it should boot into the VM.

**Current behaviour:**
When I run `nanobox run` without an internet connection it fails.

```
Building runtime :
  ✓ Starting docker container
  ! Preparing environment for build
    - Copying ssh keys into the build environment...
    - Setting up directories and permissions...
    - Cloning engine :
      Cloning into 'engine'...
      fatal: unable to access 'https://github.com/nanobox-io/nanobox-engine-elixir.git/': Could not resolve host: github.com
    
    ! FAILED TO CLONING HTTPS://GITHUB.COM/NANOBOX-IO/NANOBOX-ENGINE-ELIXIR.GIT !
    
    Exit
     128
    
    Command
     su - gonano -c "cd /opt/nanobox; siphon --prefix '  ' -- git clone https://github.com/nanobox-io/nanobox-engine-elixir.git engine"
    
    Output
       Cloning into 'engine'...
       fatal: unable to access 'https://github.com/nanobox-io/nanobox-engine-elixir.git/': Could not resolve host: github.com
    
- Cloning engine :
  Cloning into 'engine'...
  fatal: unable to access 'https://github.com/nanobox-io/nanobox-engine-elixir.git/': Could not resolve host: github.com

! FAILED TO CLONING HTTPS://GITHUB.COM/NANOBOX-IO/NANOBOX-ENGINE-ELIXIR.GIT !

Exit
 128

Command
 su - gonano -c "cd /opt/nanobox; siphon --prefix '  ' -- git clone https://github.com/nanobox-io/nanobox-engine-elixir.git engine"

Output
   Cloning into 'engine'...
   fatal: unable to access 'https://github.com/nanobox-io/nanobox-engine-elixir.git/': Could not resolve host: github.com


Error   : bad exit code(1)
Context : failed to build the code -> util:Exec:/opt/nanobox/hooks/fetch
```

**Comment by lyondhill** [comment]
Thanks for the suggestion. I tried using nanobox in the car without internet once and the experience was not good. I will look into this for sure.

**Comment by lyondhill** [comment]
I will be closing the issue because it hasnt gotten any additional requests in the last 6 months. If we gain interest we can re open it

**Comment by andersondalmina** [comment]
I think that run offline is an important feature. This week I'm traveling and the internet I'm using is very bad, so it's difficult to use nanobox.

**Comment by nasmorn** [comment]
I think it is important too. Nanobox drained a few GB on my mobile data plan pretty quickly. So I cannot develop with it at all over mobile.

**Comment by KunalKarnik** [comment]
I too think this is a very important issue! If there is no change in the boxfile.yml; offline development should be an option!

**Comment by alex-ross** [comment]
Could we please open this issue?
We understand that nanobox needs to fetch images to start the containers. But sadly we did expect that we could start a project if we already started it before.

During a power failure yesterday noone in our team and company could start a nanobox development environment and did need to fall back to other solutions.

I think this is a very important issue.

**Comment by tylerflint** [comment]
@alex-ross Thanks for the insight. Just FYI a complete ground-up rebuild of Nanobox is on the verge of being released. This new version will not have this issue. Stay tuned...

**Comment by LeCoupa** [comment]
Any news?
