### ISSUE TITLE
If terminal is too small, output doesn't update properly

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#323]
When running `nanobox deploy` output can spam smaller terminals. Likely not a big deal at all.

Exaggerated example (happens with terminals 80 columns wide as well(common default width)):
![image](https://cloud.githubusercontent.com/assets/2653109/21993176/bef81732-dbd6-11e6-94fd-e5b7df6ae9cd.png)

**Comment by glinton** [comment]
Looks like wget is the same way:
![image](https://cloud.githubusercontent.com/assets/2653109/21993386/d47e6ed4-dbd7-11e6-840a-8f84b8d4597b.png)

closing as cosmetic non-issue

**Comment by tylerflint** [comment]
Hey @glinton I think this is still something we should look into. I'm gonna keep it open if that's ok with you?

**Comment by glinton** [comment]
Probably more related to this than a new issue with compiling, but when trying to debug why `nanobox compile-app` isn't compiling the app, nanobox panics.

To view the panic, terminal has to be <40 characters wide.

```
panic: runtime error: slice bounds out of range

goroutine 51 [running]:
panic(0x936ca0, 0xc420014150)
	/home/travis/.gimme/versions/go1.7.3.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/nanobox-io/nanobox/util/display.(*Summarizer).handleLog(0xc420096300, 0xc420318c40, 0x35)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/display/summary.go:225 +0x1de
github.com/nanobox-io/nanobox/util/display.(*Summarizer).run(0xc420096300)
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/display/summary.go:146 +0x18f
created by github.com/nanobox-io/nanobox/util/display.(*Summarizer).Start
	/home/travis/gopath/src/github.com/nanobox-io/nanobox/util/display/summary.go:68 +0x3f
```

Ubuntu 16.10
Nanobox version 0.9.0 ()
