### ISSUE TITLE
`nanobox dev` doesn't open a console

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#33]
It just hangs after printing a message 'container already exists'
```
+> Opening a nanobox console:


                                     **
                                  ********
                               ***************
                            *********************
                              *****************
                            ::    *********    ::
                               ::    ***    ::
                             ++   :::   :::   ++
                                ++   :::   ++
                                   ++   ++
                                      +

                      _  _ ____ _  _ ____ ___  ____ _  _
                      |\ | |__| |\ | |  | |__) |  |  \/
                      | \| |  | | \| |__| |__) |__| _/\_

--------------------------------------------------------------------------------
+ You are in a virtual machine (vm)
+ Your local source code has been mounted into the vm, and changes in either
the vm or local will be mirrored.
+ If you run a server, access it at >> sample-go.dev
--------------------------------------------------------------------------------
HTTP/1.1 200 OK
Date: Wed, 11 Nov 2015 23:16:26 GMT
Content-Length: 24
Content-Type: text/plain; charset=utf-8

container already exists
```

`ctrl + c` or `d` doesn't disconnect either, and killing the `nanobox dev` process results in a broken terminal (no output, input printed, nor newlines)

Currently investigating if this affects more than ubuntu linux

**Comment by tylerflint** [comment]
@lyondhill is investigating this currently. It appears to have something to do with docker on the new base boot2docker image created today.

**Comment by lyondhill** [comment]
I am not sure when this happened but when nanobox-server creates the dev1 container docker complains saying "Conflicting options: -h and the network mode (--net)". Basically binding to the host network puts restrictions on the hostname the container is allowed to have.

**Comment by lyondhill** [comment]
UPDATE: the restriction has been in since the --net settings were added. The change is that when nanobox fires up the box the hostname is not being configured to #(appname}.dev. I have removed hostname setting from the dev container config so the feature works but the hostname on vagrant machine still needs to be set to the correct name

**Comment by sdomino** [comment]
this was resolved here: https://github.com/nanobox-io/nanobox-server/commit/5ce90ccc7a80ab79a34442fc5731186681166197
