### ISSUE TITLE
Hyper-V

### ISSUE THREAD

**Issue by wahmedswl** [nanobox-io/nanobox#341]
Hi,
   Is Hyper-V supported as oppose to VirtualBox as now Docker also moved to Docker and its native Hypervisor for Windows.

Thanks

**Comment by danhunsaker** [comment]
Not directly, no.  But!  Sometime soon, a new Nanobox version, with native Docker support, will be released.  At that point, Docker's own Hyper-V implementation will be used under the hood, and VirtualBox will not be required any longer.

Indeed, VirtualBox wouldn't have been involved at all if Docker Native had been ready for both Windows and macOS when Nanobox was in early development.

**Comment by tylerflint** [comment]
This will be released on Monday, February 6 :)

**Comment by wahmedswl** [comment]
That would be great 👍
