### ISSUE TITLE
make config smarter

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox#355]
nanobox configure should look to see if docker is installed before allowing it as an option
same goes for docker-machine

should also set limits based on the machine its on

**Comment by danhunsaker** [comment]
Asking about VM disk size would also be helpful

**Comment by lyondhill** [comment]
we are discussing that internally and will make a decision on that shortly.

**Comment by glinton** [comment]
What was the decision on this? It seems like just setting it to a few hundred gigs would work, since its a virtual disk and doesn't allocate the space. With the extra image fix in place, disk usage seems like it would stay somewhat reasonable.

**Comment by lyondhill** [comment]
the "smarter" part has been put on the back burner. You can set your vm disk using the config command now. This issue was related to detecting which providers you have available on your machine and not disk specifically
