### ISSUE TITLE
Print meaningful error when yaml incorrectly formatted

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#359]
Currently, if there is a yaml formatting error in the boxfile (tabs), nanobox prints out an 'invalid engine' error:

#### Output:
```
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: INVALID ENGINE !!!
    
    Uh oh, the engine provided is not something we can retrieve. You might
    want to check out our getting-started guide on specifying an engine:
    
    https://docs.nanobox.io/boxfile/run-config/
    
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
```

#### Bad yaml:
>![image](https://cloud.githubusercontent.com/assets/2653109/22701748/cc7ba2e2-ed1b-11e6-9157-e6c9840db557.png)

**Comment by lyondhill** [comment]
This issue was moved to nanobox-io/nanobox-docker-build#113
