### ISSUE TITLE
[Win] Custom location / Missing dependencies

### ISSUE THREAD

**Issue by Skowt** [nanobox-io/nanobox#37]
I'm unable to get the Windows bundle to install properly using Windows 10 x64. Summary:

- I've attempted using a custom location as well as no location (in the installer) and while the folder get created, nothing else does.

- I found a folder under C:/ drive even though I installed on an alternative drive and when run with CMD, it complained about Vagrant. Then when CMD was run as administrator, it complained about VirtualBox.

- The installer itself ran without an issue or error. The problems came when trying to find and run nanobox itself.

- [Suggestion] Ensure that Vagrant or VirtualBox is not installed before attempting to install. And if it was installed already, don't remove it when uninstalling Nanobox.

**Comment by sdomino** [comment]
@Skowt thank you for submitting this. We actually haven't had a change to do much Windows testing yet :/ and will get to this as soon as we can. We really appreciate your help pioneering our Windows effort.

**Comment by glinton** [comment]
Thanks for the suggestion, I'll look more into how the WiX Toolset handles bundled software. I just assumed it had some smart checks in place. The actual bit of code is [here in nanobox-installer.](https://github.com/nanobox-io/nanobox-installer/blob/master/windows/build-windows-all.ps1#L77)

**Comment by Skowt** [comment]
Hey @glinton, I might be wrong here but shouldn't this code not be commented out? So NanoBox msi is downloaded? or is the msi the actual code itself?

    # Download nanobox
    $NanoboxSourceURL =        "https://s3.amazonaws.com/tools.nanobox.io/installers/windows/nanobox.msi"
    $NanoboxDest      = "$($NanoboxTmpDir)/nanobox.msi"

    # Write-Host "Downloading nanobox: $($NanoboxVersion)"
    # $client = New-Object System.Net.WebClient
    # $client.DownloadFile($NanoboxSourceURL, $NanoboxDest)
    # Write-Host "Downloaded nanobox: $($NanoboxVersion)"

    # Write-Host "Copying nanobox: $($NanoboxVersion)"
    Copy-Item nanobox.msi $NanoboxDest

**Comment by glinton** [comment]
@Skowt: I found myself always building the two installers together so I found it faster to just [copy](https://github.com/nanobox-io/nanobox-installer/blob/master/windows/build-windows-all.ps1#L36) the recently created 'nanobox.msi' into the nanobox-bundle's build location. (Rather than wait for it to upload to s3 then download it again)

**Comment by tylerflint** [comment]
@Skowt Thanks for finding this. The help is greatly appreciated! 

Nanobox has been completely re-written from the ground up, and we just released the v1 into beta this week. Also, the windows installer has been completely rebuilt and windows functionality is now a first-class-citizen. We would love to get your feedback on the new version. The new guides are still a WIP but should be usable within the next week. If you're interested, we'd love to talk with you on irc #nanobox or we can bring you into our slack channel as well.

Additionally, Nanobox and Nanobox Cloud have been merged into a unified process. If you would be interested in early access to the private beta please let me know and I can get you an access token.

Just reach out to hello@nanobox.io and we can get you going.

I really appreciate your help on this. I'll go ahead and close this ticket and hope to hear from you directly.
