### ISSUE TITLE
nanobox.io is down

### ISSUE THREAD

**Issue by Inumedia** [nanobox-io/nanobox#400]
Hi,

Not sure where to send this (I don't see a twitter, status page, or an ops person I should email), but nanobox.io appears down to me.

![image](https://cloud.githubusercontent.com/assets/856822/23576974/34c04420-0081-11e7-83de-c7d38513c13c.png)

Pls fix kty 😘

**Comment by tylerflint** [comment]
@Inumedia Thanks for the heads up. The alerts woke me up and we got the problem figured out. Thanks so much!
