### ISSUE TITLE
Mirror hardware settings of node in dry-run VM

### ISSUE THREAD

**Issue by benoneal** [nanobox-io/nanobox#409]
Had an issue recently where the production node had too little memory, and so services were constantly being killed and restarded. It's a node app, and npm was attempting to log the errors, but can't write to the `app/` directory. npm can't be configured to log anywhere except `cwd`, so this was masking the memory error. 

Of course, `dry-run` worked perfectly, so this was very confusing. 

If `dry-run` mirrored the production node hardware environment as close as possible, this issue would have been surfaced earlier, and would have been quicker to debug (not requiring full deploys).

**Comment by danhunsaker** [comment]
To replicate the prod environment even closer, matching the kernel would be even better.  Doing that, though, is ... not really feasible under the current design.  Still, in the interest of simulating production as accurately as possible, being able to match the kernel version as well as the resources would be very useful.

**Comment by lyondhill** [comment]
This sounds like a great idea benoneal. There are a few things I think we need to consider first:
1 This situation only works when running docker-machine.
2 Unlike production, local puts all your apps on a shared vm, knowing which app we should mirror is not possible.
3 Production comes long after the vm has been created and developed in. 
4 When deploying we do all the compiling and prepping on local, depending on the language it probably needs more resources then your production vm does.

With that in mind I still think there is something we could do here. I am just not sure what it is.
Thanks for your suggestion.
