### ISSUE TITLE
nanobox on proxy failure

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox#418]
Proxy evars are not getting passed into containers.

**Comment by notxarb** [comment]
Proxy evars need to be set in the vm, and containers.

**Comment by notxarb** [comment]
Lack of proxy settings in the vm will make it so that `docker pull <image>` fails.

Lack of proxy settings inside containers make hooks fail.

**Comment by rlyders** [comment]
Running on Windows 7 Enterprise 64-bit:

I installed nanobox and then followed the quickstart instructions for nanobox-feathers: https://github.com/nanobox-quickstarts/nanobox-feathers#readme

```bash
nanobox dns add local feathers.dev
```

		CONFIGURE NANOBOX
		---------------------------------------------------------------
		Please answer the following questions so we can customize your
		nanobox configuration. Feel free to update your config at any
		time by running: 'nanobox configure'

		(Learn more at : https://docs.nanobox.io/local-config/nanobox-config-yml/)

		How would you like to run nanobox?
		  a) Inside a lightweight VM
		  b) Via Docker Native

		  Note : Mac users, we strongly recommend choosing (a) until Docker Native
				 resolves an issue causing slow speeds : http://bit.ly/2jYFfWQ

		Answer: a

		How many CPU cores would you like to make available to the VM (1-4)?
		-------------------------------------------------------------------
		  Note : we recommend 2 or more

		Answer: 2

		How many GB of RAM would you like to make available to the VM (2-4)?
		-------------------------------------------------------------------
		  Note : we recommended 2 or more

		Answer: 2

		Would you like to enable netfs for faster filesystem access (y/n)?
		-------------------------------------------------------------------
		  Note : We HIGHLY recommend (y). Using this option may prompt for password

		Answer: y

			  **
		   *********
		***************   [√] Nanobox successfully Configured!
		:: ********* ::   ------------------------------------------------------------
		" ::: *** ::: "   Change these settings at any time via : 'nanobox configure'
		  ""  :::  ""
			"" " ""
			   "

		√ Reserving IPs

```bash
nanobox run yarn start
```

		Starting Nanobox :

		--------------------------------------------------------------------------------
		+ HEADS UP:
		+ Nanobox will run a single VM transparently within VirtualBox.
		+ All apps and containers will be launched within the same VM.
		--------------------------------------------------------------------------------

		  √ Launching VM
		  √ Configuring Network
		  √ Loading kernel modules
		  √ Cleaning DHCP
		  √ Regenerating Docker certs
		  √ Joining virtual network

		Building bridge :
		  ! Pulling nanobox/bridge image

		Error   : Error: No such image: nanobox/bridge
		Context : failed to setup the network bridge -> failed to pull docker image (nanobox/bridge)

		Enter to continue:

```bash
nanobox-machine ssh nanobox
```

```bash
sudo sh -c 'cat <<EOF >>/var/lib/boot2docker/profile
export http_proxy=http://myuser:mypwd@myproxyip:80
export https_proxy=http://myuser:mypwd@myproxyip:80
export HTTP_PROXY=http://myuser:mypwd@myproxyip:80
export HTTPS_PROXY=http://myuser:mypwd@myproxyip:80
EOF
'

sudo sh -c 'cat <<EOF >>/etc/profile
export http_proxy=http://myuser:mypwd@myproxyip:80
export https_proxy=http://myuser:mypwd@myproxyip:80
export HTTP_PROXY=http://myuser:mypwd@myproxyip:80
export HTTPS_PROXY=http://myuser:mypwd@myproxyip:80
EOF
'
exit

```
** RESTART nanobox VM **

```bash
nanobox run yarn start
```
** Now I get the following error mounting code base, but that is a separate issue **
		D:\Users\myuser\Documents\dev\nanobox-feathers>nanobox run yarn start
		√ Skipping (already running)
		Building bridge :
		  √ Pulling nanobox/bridge image
		  √ Starting docker container
		  √ Setting up container
		  √ Configuring
		Administrator privileges are required to start the vpn.
		Another window will be opened as the Administrator and permission may be requested.
		Enter to continue:


		Preparing environment :
		  * Mounting codebase

		Administrator privileges are required to modify network shares.
		Another window will be opened as the Administrator and permission may be requested.
		Enter to continue:


		  * Mounting codebase

		myuser's password is required to mount a Windows share. (must be your Windows Live password if linked)
		Password:

		  ! Mounting codebase

		Error   : cifs:exit status 1
		Context : failed to init docker client -> failed to setup env mounts -> failed to mount the code share on the provider

		Enter to continue:

**Comment by glinton** [comment]
Regarding the mounting issues: I wonder if the mount is trying to follow the proxy? If so, we'd just need to add the endpoint as a `no_proxy` variable.

Regarding getting the proxy vars in automatically: our initial research, that docker-machine was importing `_proxy` vars if they were present on machine create, was false. The only way I could get them into the `profile` automatically was as follows:

```
docker-machine create -d virtualbox \
  --engine-env HTTP_PROXY=$HTTP_PROXY \
  --engine-env HTTPS_PROXY=$HTTPS_PROXY \
  --engine-env NO_PROXY=$NO_PROXY \
  --engine-env http_proxy=$http_proxy \
  --engine-env https_proxy=$https_proxy \
  --engine-env no_proxy=$no_proxy \
    nanobox
```

This still doesn't expose the variables to the containers however. To populate container proxy settings run the following to generate an env-var file
```
grep -i proxy /var/lib/boot2docker/profile  | awk '{print $2}' | tr -d '"' > proxy.env
```

This must be referenced when starting a container as follows:
```
docker run --env-file ~/proxy.env --rm busybox env
```

**Comment by rlyders** [comment]
**CONTINUED**
_**I had to rush out before I finished uploading the full test scenario...here are the last few steps....**_

Lyon asked me to run ...
`net share
`

Which resulted in the following ...

```
	Share name   Resource                        Remark

	-------------------------------------------------------------------------------
. . .
	nanobox-cb6a85feb309103959705dd815ac4b4e
				 D:/Users/myuser/Documents/dev/nanobox-feathers
...
				 The command completed successfully.

```

Lyon asked me to run the following to work around the issue mounting the code base...

```
sudo mkdir -p /share/cb6a85feb309103959705dd815ac4b4e/code
sudo mount -t cifs -o sec=ntlmssp,username=myuser,password=mypwd '//mypooter/nanobox-cb6a85feb309103959705dd815ac4b4e' /share/cb6a85feb309103959705dd815ac4b4e/code
```

Finally, I was able to get past the codebase mounting issue so that the final issue is shown below related to git not being able to clone nanobox-engine-nodejs.git...

`nanobox run yarn start
`
```
	--------------------------------------------------------------------------------
	+ HEADS UP:
	+ This is the first build for this project and will take longer than usual.
	+ Future builds will pull from the cache and will be much faster.
	--------------------------------------------------------------------------------

	Building runtime :
	  √ Pulling nanobox/build image
	  √ Starting docker container
	  ! Preparing environment for build
	- Cloning engine :
	  Cloning into 'engine'...
	  fatal: unable to access 'https://github.com/nanobox-io/nanobox-engine-nodejs.git/': gnutls_handshake() failed: An unexpected TLS packet was received.

	! FAILED TO CLONING HTTPS://GITHUB.COM/NANOBOX-IO/NANOBOX-ENGINE-NODEJS.GIT !

	Exit
	 128

	Command
	 su - gonano -c "cd /opt/nanobox; siphon --prefix '  ' -- git clone https://github.com/nanobox-io/nanobox-engine-nodejs.git engine"

	Output
	   Cloning into 'engine'...
	   fatal: unable to access 'https://github.com/nanobox-io/nanobox-engine-nodejs.git/': gnutls_handshake() failed: An unexpected TLS packet was received.


	Error   : failed to execute hook (fetch) on 150aefb44b0eb747bb554dfbd315db1bb93ecb0978a1fc12285cbf36f03fad05: util:Exec:/opt/nanobox/hooks/fetch: bad exit code(1):
	Context : failed to build the code

	Enter to continue:
```
