### ISSUE TITLE
[Win] Missing Virtual Box

### ISSUE THREAD

**Issue by Tomino2112** [nanobox-io/nanobox#42]
I have downloaded the windows package with Vagrant and VirtualBox included, didn't change anything along the way, all default installation and got this error:

`Missing dependency 'Virtualbox'. Please download and install it to continue (https://www.virtualbox.org/wiki/Downloads).`

**Comment by rajeevmehrotra** [comment]
I was able to fix this issue.  The installer appears to not add the virtualbox to your PATH.  So you need to add it yourself, the path is something like:

`C:\Program Files\Oracle\VirtualBox\`

**Comment by sdomino** [comment]
@Tomino2112, @rajeevmehrotra - We haven't had a lot of time to thoroughly test Windows yet, so we're trying to address these as soon as they come up. I believe that @glinton is looking into our Windows installer to fix some of these issues.

**Comment by bouiboui** [comment]
Thanks @rajeevmehrotra, worked for me

**Comment by rajeevmehrotra** [comment]
@bouiboui did you get a separate error after this was fixed? In particular this error: #44

**Comment by bouiboui** [comment]
I haven't gone further yet, I will try and report.

**Comment by glinton** [comment]
Potential fix - #103 - thanks to @mattn
