### ISSUE TITLE
Enable mfsymlinks by default on Windows

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#422]
Since #269 Nanobox supports [mfsymlinks](https://wiki.samba.org/index.php/UNIX_Extensions#Minshall.2BFrench_symlinks) for netfs on Windows.

However, this must be enabled manually via `nanobox config set netfs_mount_opts mfsymlinks` ATM.

I'd suggest to set this option by default. If one does not use netfs, it won't be used. If one does use netfs, he'll not loose anything but get a more usable setup instead given that symlinks actually work in all cases.

**Comment by lyondhill** [comment]
this is a good suggestion. I will discuss it and it will probably make it into 2.1.1
