### ISSUE TITLE
Error "unable to communicate with Docker" on Shippable CI

### ISSUE THREAD

**Issue by mbrodala** [nanobox-io/nanobox#425]
Currently I try to get Nanobox working on Shippable CI according to the [workflow docs](https://docs.nanobox.io/workflow/ci-cd/). However, an error occurs:

```
Starting Nanobox :
  Setting up custom docker network... :
  Joining virtual network :

Error   : unable to communicate with Docker
Context : failed to initialize docker for provider
```

While the docs say that *The CI/CD server cannot be a Docker container* I sincerely hope that there is a way to get this running. Docker in Docker itself [should work](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/#the-solution) AFAIS.

This is how Shippable launches the build container:

```
docker run -d --privileged=true --net=bridge -v /home/shippable/cexec:/home/shippable/cexec -v /usr/bin/docker:/usr/bin/docker -v /home/shippable/cache:/home/shippable/cache -v /tmp/cexec:/tmp/cexec -v /var/run/docker.sock:/var/run/docker.sock -v /build:/build --name=c.exec.<project>.<build>.1 --entrypoint=/home/shippable/cexec/build.sh -e RUN_MODE=production -e SHIPPABLE_API_URL=https://api.shippable.com -e SHIPPABLE_API_RETRY_INTERVAL=3 -e SHIPPABLE_CONTAINER_NAME=c.exec.<project>.<build>.1 -e SHIPPABLE_IS_OFFICIAL_IMAGE=true -e SHIPPABLE_IS_LEGACY_IMAGE=false drydock/u14phpall:prod
```

Notice that it is possible to [extend this command line](http://docs.shippable.com/ci/shippableyml/#pre_ci_boot).

**Comment by lyondhill** [comment]
same problem as #427 just manifest in a different way. More details are over there
