### ISSUE TITLE
Server being not responsive after scaling

### ISSUE THREAD

**Issue by tfortier** [nanobox-io/nanobox#446]
I scaled up from 2 to 4 web nodes and the third one seems to be working but the fourth one can't spin-up php-fpm :

```
2017/05/17 20:40:16 [error] 243#0: *1179 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: localhost, request: "
GET /nanobox.php HTTP/1.0", upstream: "fastcgi://unix:/data/var/tmp/php.sock:", host: "nano.radiox.com" 
```

Here the client is nginx itself. 8080 talks with 8181, both nginx but 8080 caches pages. Fither more, when I access my test page, I see, host 1, host2, host 3 and on the fourth reload, gateway error.

That's from /data/var/nginx/error.log

It served 4 requests successfully, then errored, served 2 more, then errored again 4 times before tons of 502s and stuff

This was during a load test so there was quite a bit of traffic.

**Comment by lyondhill** [comment]
This issue was moved to nanobox-io/nanobox-hooks-code#21
