### ISSUE TITLE
Disallow running as superuser

### ISSUE THREAD

**Issue by danhunsaker** [nanobox-io/nanobox#451]
Many new user issues are caused by using `sudo` to run various commands. We should detect when Nanobox is being run with superuser rights already available, and bail out with a warning similar to the following:

> Nanobox should not be run with full administrative privileges. It will ask for them when it needs them, but should otherwise be run with your normal capabilities. Please try again.

or some similar wording to avoid using `sudo`, etc.

**Comment by lyondhill** [comment]
This is a great idea. The super user issue has come up a few times. I worry there may be a use case where someone needs to run nanobox as super (i cant think of one).

We really have 2 branches here, 1 disallow super user, or 2 make nanobox work under both contexts.

**Comment by lyondhill** [comment]
@tylerflint What do you think?

**Comment by tylerflint** [comment]
My vote would be to disallow superuser.

**Comment by lyondhill** [comment]
ok cool. I think I can whip up a pull request. This would honestly solve a few issues.
