### ISSUE TITLE
OSX /etc/exports removeDuplicates can have false positives when looking for child folders

### ISSUE THREAD

**Issue by notxarb** [nanobox-io/nanobox#459]
Example:

If I have 2 projects in folders as follows:

    /Users/braxton/src/website
    /Users/braxton/src/website_blog

This will incorrectly identify `website_blog` as being a child of `website` and not put it in the `/etc/exports` file.
https://github.com/nanobox-io/nanobox/blob/master/util/provider/share/share_darwin.go#L309

It should probably be something like this:

    if strings.HasPrefix(path, originalPath+"/") {

**Comment by lyondhill** [comment]
Good find Braxton I can get a pull request in for that quickly
