### ISSUE TITLE
Typo on mac download page

### ISSUE THREAD

**Issue by brianseitel** [nanobox-io/nanobox#46]
Says "Pleas send bugs to Github". Should be "please".

http://d.pr/i/swos

**Comment by sdomino** [comment]
@brianseitel thank you for this. We're currently compiling quite a list of nanobox.io issues, so we'll add this to the list and get it out as soon as we can.

**Comment by Tolmark12** [comment]
@brianseitel Thanks for the catch, really appreciate it. Fixed.
