### ISSUE TITLE
Ensure protocol is either tcp or udp on `deploy`

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#464]
This validation is [present, and works great in `deploy dry-run`](https://github.com/nanobox-io/nanobox/blob/master/generators/router/services.go#L84), but this should also be validated for `deploy`

**Comment by lyondhill** [comment]
https://github.com/nanobox-io/nanobox-docker-build/commit/f0af1d016953ba4d604a615ebcb34e32c667efdc
