### ISSUE TITLE
Mac binary manually install does not work

### ISSUE THREAD

**Issue by hvnsweeting** [nanobox-io/nanobox#470]
Command from README file 
```
$ wget https://s3.amazonaws.com/tools.nanobox.io/nanobox/v1/linux/amd64/nanobox
```

```
[hvn:~/bin] [dream] 4s $ ./nanobox
-bash: ./nanobox: cannot execute binary file: Exec format error
[hvn:~/bin] [dream] 6s 126 $ file nanobox
nanobox: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, not stripped
```

The file seems only support linux.

**Comment by danhunsaker** [comment]
Indeed. Note that the path includes `linux` as one of the subdirectories the binary is within.

Additionally, this link is to an outdated version of the app. You'll want to [log in to your Nanobox account](https://dashboard.nanobox.io/) and download the Mac installer from there.

The README certainly needs updating, though. Thanks for bringing that up!

**Comment by hvnsweeting** [comment]
yes I saw that. So there is no other way to manualy install it? 
I don't like the idea of have to enter my password to install and starting VM.

Then I installed go app "the go way" by `go get ...` and got nanobox, but after logged in, ran "run", I got 

```
+ HEADS UP:
+ Nanobox will run a single VM transparently within VirtualBox.
+ All apps and containers will be launched within the same VM.
--------------------------------------------------------------------------------

  Launching VM :

Error   : : exec: "nanobox-machine": executable file not found in $PATH
Context : failed to create the provider
```

So the binary from Nanobox.io is the only way to install it, right?

**Comment by lyondhill** [comment]
The current intended behavior of nanobox is to install with the nifty installers we provide here https://dashboard.nanobox.io/download Nanobox requires some additionally binaries that it includes in the installers (nanobox-machine, nanobox-vpn and a few others).
