### ISSUE TITLE
Link at the bottom of README is broken

### ISSUE THREAD

**Issue by hvnsweeting** [nanobox-io/nanobox#471]
```
$ curl https://nanobox.io/open-source -I
HTTP/1.1 404 Not Found
Content-Length: 169
Content-Type: text/html
Date: Tue, 20 Jun 2017 07:38:02 GMT
Server: nginx/1.12.0
```

it is 404.

**Comment by danhunsaker** [comment]
Sorry about that! The page was removed around the time Nanobox came out of beta, and hasn't been re-created, yet.

**Comment by lyondhill** [comment]
Talked to Scott and he will get that created. Thanks for reporting

**Comment by Tolmark12** [comment]
I'll get this fixed, thanks for the catch @hvnsweeting

**Comment by glinton** [comment]
Looks like this page has life again, thanks everyone.
