### ISSUE TITLE
Add some help text/context for tunnel command

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#472]
Currently when establishing a db tunnel, the output just says: "listening on port 5432".

We should expand this to provide some helpful context and directions. I can provide the content when ready.

**Comment by lyondhill** [comment]
the tunnel command is not very descriptive. A better message would be appreciated. Place it here and I will make a pull request

**Comment by sanderson** [comment]
How's this?

```
--------------------------------------------------------------------------------
+ Secure tunnel established
+ Use the following credentials to connect to [component.id]
--------------------------------------------------------------------------------

Host: 127.0.0.1
Port: [port]
User: available in your dashboard (if applicable)
Pass: available in your dashboard (if applicable)
```

**Comment by tylerflint** [comment]
Looks great!
