### ISSUE TITLE
Stream production logs in the CLI

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox#474]
This feature has been talked about for a while, but I just wanted to make sure it's documented. We need to add the ability to stream production logs in the CLI. The command would need a remote/app from which to pull logs with the ability to either stream the live-stream logs or view a set number of historical logs. Here are some potential command options:

```bash
nanobox log [remote] [-l --live] [-c --count=]
# OR
nanobox log [remote] [-t --tail] [-n --number=]
```

**Comment by lyondhill** [comment]
@jedgalbraith is this possible through odin yet?

**Comment by jedgalbraith** [comment]
No, not yet. I've created a companion issue in odin for it. https://github.com/nanobox-io/nanobox/issues/474

**Comment by lyondhill** [comment]
ok thanks jed. I will put this on my list.

**Comment by glinton** [comment]
Also support `dry-run` and `local`
