### ISSUE TITLE
Windows 10 update breaking changes

### ISSUE THREAD

**Issue by johnrazmus** [nanobox-io/nanobox#486]
When already on Windows 10 and installing their latest big "feature" update, Nanobox no longer was able to connect to the VM.

Reverting the Windows 10 update allowed Nanobox to resume working.

![pasted image at 2017_07_03 10_22 am](https://user-images.githubusercontent.com/1461626/27804067-d7e57f70-5fe1-11e7-8966-3af7f122a47f.png)

![pasted image at 2017_07_03 10_48 am](https://user-images.githubusercontent.com/1461626/27804074-e037bbfc-5fe1-11e7-8cad-eadf10a46f44.png)

**Comment by notxarb** [comment]
Can you try running `netsh Winsock reset`

**Comment by lyondhill** [comment]
can you try opening cmd as admin and run `netsh Winsock reset`

**Comment by johnrazmus** [comment]
Will have to be a bit later - would require re-updating the PC to Windows 10.

If anyone else is actively experiencing this that can run it, awesome - otherwise it might be a day or two

**Comment by lyondhill** [comment]
After installing the windows update all was right in the world
