### ISSUE TITLE
NFS mount fails on mac os due to terminal being case-insensitive

### ISSUE THREAD

**Issue by CalvinWalzel** [nanobox-io/nanobox#491]
Given that a folder name is `Projects` and you cd into the folder in a mac os terminal using `cd projects` (which is valid and results in `Calvins-MacBook-Pro:projects calvin$`), starting a nanobox with `nanobox run` fails with:

```
Error   : mount: output: mount: 192.168.99.1:/Users/calvin/projects/rails-app failed, reason given by server: Permission denied
mount: mounting 192.168.99.1:/Users/calvin/projects/rails-app on /share/83d0a9501468d27d5455238eb4feb03c/code failed: Bad file descriptor
exit status 110
 err:exit status 1
Context : failed to init docker client -> failed to setup env mounts -> failed to mount the code share on the provider
```

This is due to nanobox-desktop taking the path as it is being represented in the mac os terminal (case-insensitive) and using it with the vm (case-sensitive).

If you move into the path with `cd Projects` (mind the capital p) and then initialise the nanobox, everything works as expected.

**Comment by glinton** [comment]
Here is a binary someone can test with (darwin/mac only)
[nanobox-491-darwin.zip](https://github.com/nanobox-io/nanobox/files/1131815/nanobox-491-darwin.zip)
1. Download and unzip binary
2. `mkdir /tmp/Test`
3. ` cd /tmp/test #it's important 'echo $PWD' shows /tmp/test`
4. Add a boxfile (the fast version)
```
cat > boxfile.yml <<EOF
run.config:
  engine: none
EOF
```
5. `nanobox run`
  it should fail to mount, `nanobox destroy`
6. `~/Downloads/nanobox-491-darwin run`
  it should work

**Comment by danhunsaker** [comment]
At least one successful test, while chatting with a user (@aidonhudson) in Slack. This does seem to fix the issue.

Hopefully others will chime in, but for my part, LGTM!

**Comment by glinton** [comment]
I'm worried this may have caused other issues, I'll leave this here for reference later on:
A user in slack reported the following:

>nanobox output
>```
>Error   : failed to add share checkexports: exports:2: got host/group with no directory?: “”
>exit status 1
>Context : failed to init docker client -> failed to setup env mounts -> failed to mount the code share on the provider -> failed to add share
>```

>/etc/exports
>```
>“” 192.168.99.51 -alldirs -mapall=501:20
>```
