### ISSUE TITLE
Update the tunnel command to allow for more flexible port binding

### ISSUE THREAD

**Issue by sanderson** [nanobox-io/nanobox#496]
This [proposed functionality](https://github.com/nanobox-io/odin/issues/202) (_private repo_) allows multiple ports for components to be available in production.

```bash
# Pattern:
nanobox tunnel [component.id] [local-port]:[remote-port]

# Examples:
nanobox tunnel data.db            # would bind to the default port of the service locally and forward to the same remote port
nanobox tunnel data.db 3306       # would bind to 3306 locally and forward to 3306 remotely
nanobox tunnel data.db 3308:3306  # would bind to 3308 locally and forward to 3306 remotely
```

This functionality becomes really important for data services that offer different functionality on different ports, like RethinkDB. The RethinkDB server includes an admin UI access on `localhost:8080`, which is really the only way they provide to manage data other than through language specific adapters. To access this UI for a production database, you could establish a tunnel that forwards to 8080:

```bash
nanobox tunnel data.rethink 8081:8080
```

You'd then be able to access the production RethinkDB admin UI at `http://127.0.0.1:8081`.

**Comment by lyondhill** [comment]
this would require a change in odin before it can be implemented here. (notes on that change have been posted)

**Comment by sagivf** [comment]
@sanderson So is there a workaround for the time being? Not sure I fully understand.
Also I think it goes without saying this should somehow be secured...

**Comment by sagivf** [comment]
@glinton this seems to work but the RethinkDB admin doesn't load... The requests seems to stuck and only partially load.

**Comment by danhunsaker** [comment]
This is a known issue, which we're still investigating. I need to fire up an app with RethinkDB and do some deep inspection of what's going on.

**Comment by sagivf** [comment]
Thanks, no rush. I think I've seen similar behavior in the past, might be some RethinkDB specific issue. Some requests do complete(not many).

**Comment by sagivf** [comment]
@danhunsaker Hey. since this is still an issue, shouldn't we open this bug, or at open a new one?

**Comment by glinton** [comment]
I would say open a new issue for rethinkdb specifically. Since this issue (custom ports) has been addressed. TIA

**Comment by sanderson** [comment]
To second @glinton, it'd probably be best to add this as a new issue here: https://github.com/nanobox-io/nanobox-docker-rethinkdb

**Comment by sagivf** [comment]
Cool, done - https://github.com/nanobox-io/nanobox-docker-rethinkdb/issues/5
