### ISSUE TITLE
Allow downloading `nanobox` before becoming a registerred user

### ISSUE THREAD

**Issue by saun4app** [nanobox-io/nanobox#498]
## Background Information

Less than a week ago, I downloaed `nanobox`, played with it a bit, and most importantly have had great user experience in interacting with the `nanobox team` via chat [nanoboxio.slack.com](nanoboxio.slack.com). The `nanobox engineers` are the best in engaging with users that I have experienced.
`nanobox` has a great product, the quality of user engagement of off the top.  

However, in my experience, the Barriers to entry is unexpectedly high.  i.e., Going from finding `nanobox` at `nanobox.io` and running a hello world type `nanobox` app requires unexpected level of effort.

Here are the things I typically look for when assessing a new tool:

1. Find out the advantages and limitations compared to other products from the web site. It is nearly impossible.  All marketing material say the product is the best (uninformative).

2. Find out the advantages and limitations by trying it out (download and install) the product.
Before taking this step I want to find out the level of effort for installing (and more importantly) uninstalling the product.  My main concern is not able to uninstall the product easily and cleanly.

I prefer a product with an installer (e.g., .deb).  Seeing a clear instillation instruction helps me to decide if I should spend the time and effort to try the product.

I *visited* and *skipped* `nanobox.io` multiple times in the past few years.

I did not find information about `nanobox`'s advantages and limitations

- for development compared to using docker and docker-compose from development or other "better than docker alone" tools. 
- for deployment compared to many other tool.

The [Getting Started](https://guides.nanobox.io/) or [Install Nanobx](https://docs.nanobox.io/install/) do not offer step-by-step instruction for installing `nanobox`.  The *implication* is that you need to register before installing `nanobox`.  I did not what to take the time and effort to register, install `nanobox` before knowing the level of effort to install and clean up after `nanobox`.

After installing, `nanobox`, I thought the installation failed [issues/497](https://github.com/nanobox-io/nanobox/issues/497).

## Suggestion

I would like to suggest
- allowing downloading `nanobox` before becoming a resister
- adding something like the following to [Install Nanobx](https://docs.nanobox.io/install/):

Downloading and installing `nanobox`.

```
dpkg -i https://dashboard.nanobox.io/download/nanobox_2_amd64.deb
nanobox configure
nanobox version
```

Uninstalling `nanobox`:
```
nanobox implode
```

Please note that you need to register at https://dashboard.nanobox.io/signup before running `nanobox configure` to install `nanobox`.

This information (instruction) helps me to know that I can try out `nanobox` to learning about it, and uninstall it without great effort and leaving a messy system (just knowing that it uses a installer).

**Comment by lyondhill** [comment]
Thanks for your input and feedback. The installation process being behind registration actual came about later in the development cycle of nanobox and was an intentional change. It allows us to see when a user is having an issue and track failure through our logging solution.
I think it would be a good idea to  make it clear that the implode is a part of the uninstall process.

**Comment by saun4app** [comment]
@lyondhill, I suspect that there is business decision behind wanting the users to register before downloading.  All I am suggesting is to show step-by-step of the entire nanobox install process to all users, even though, the actual download is for registered users only.

**Comment by glinton** [comment]
I'm going to tag @sanderson and close this since this is more of a documentation suggestion.

**Comment by glinton** [comment]
@saun4app feel free to follow/comment on this issue: nanobox-io/nanobox-docs/issues/40
