### ISSUE TITLE
`nanobox engine publish` fails with 'file exists'

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#50]
`nanobox engine publish` fails with '~/.nanobox/engines/golang: file exists'
```
$ nanobox engine publish
+> Authenticating...
+> Creating release...
+> Verifying engine is publishable...
+> Checking for existing engine on nanobox.io
A fatal error occurred (See ~/.nanobox/nanobox.log for details). Exiting...
```
```
$ tail ~/.nanobox/nanobox.log 
2015-11-18 11:52:16 FATAL [commands/engine/publish] os.Create() failed - mkdir ~/.nanobox/engines/golang: file exists
2015-11-18 11:52:16 *LOG* Closing log now
```
```
$ nanobox -v
nanobox v0.16.5
```

**Comment by tylerflint** [comment]
I think the underlying issue here is file permissions. I'm guessing somehow the ~/.app/engines directory was created with root permissions. @glinton are you still in a position that you could confirm this?

**Comment by glinton** [comment]
@tylerflint The 'golang' directory is owned by my current user and has 755 permissions.

**Comment by glinton** [comment]
I think the issue is something always tries to create the engine dir `[commands/engine/publish] os.Create() failed - mkdir ~/.nanobox/engines/golang: file exists`. Since nanobox created it the first time I published, it throws an error.

**Comment by glinton** [comment]
Just verified as it has been a few versions since this bug was filed and same(ish) results.
```sh
# updated cli
me@mine:nanobox-engine-golang$ nanobox -v
nanobox v0.16.15

# try again
me@mine:nanobox-engine-golang$ nanobox engine publish
+> Authenticating...
+> Creating release...
+> Verifying engine is publishable...
+> Checking for existing engine on nanobox.io
A fatal error occurred (See /home/me/.nanobox/nanobox.log for details). Exiting...me@mine:nanobox-engine-golang$ less /home/me/.nanobox/nanobox.log
# also note lack of newline^ (gross)

# checking it out
me@mine:nanobox-engine-golang$ tail /home/me/.nanobox/nanobox.log
2015-12-10 16:14:58 FATAL [commands/engine/publish] os.Create() failed - mkdir /home/me/.nanobox/engines/go: file exists
2015-12-10 16:14:58 *LOG* Closing log now
```

**Comment by Flat** [comment]
I don't have an account so I can't test this, but it looks like when publishing the engine the script is supposed to create a temporary directory for the engine it already exists so it throws an error.


>commands/engine/publish.go:196
```Go
// create the temp engines folder for building the tarball
	tarPath := filepath.Join(config.EnginesDir, release.Name)
	if err := os.Mkdir(tarPath, 0755); err != nil {
		Config.Fatal("[commands/engine/publish] os.Create() failed", err.Error())
	}
```

I suspect using an actual temporary directory instead of the engines directory - and deleting all the temp folders created when done - would fix this issue.

**Comment by tylerflint** [comment]
This looks great. Thanks for your help on this!

**Comment by glinton** [comment]
The `defer` statements must have failed, or were not present, when I published previously. Starting totally fresh on a new engine, the meta.json and 'tarPath' do get removed on a successful `publish`.  I found that if [`MkdirAll`](https://golang.org/pkg/os/#MkdirAll) is used (instead of Mkdir), it will not exit badly if the directory exists.  I'll open a pull request with the change in place

**Comment by sdomino** [comment]
@glinton thanks for finding this, I usually try and do MkdirAll, not sure what happened here.
