### ISSUE TITLE
Load evar(s) from .env file

### ISSUE THREAD

**Issue by zedalaye** [nanobox-io/nanobox#509]
Given a .env file containing things like:

```
ENV1=value1
ENV2=value2
```

Could it be possible to add a feature to nanobox cli to load these environment variables from one or more files ? like `nanobox evar load local .env .env.development`

**Comment by glinton** [comment]
It should also allow 
```
export KEY=VAR
```

**Comment by danhunsaker** [comment]
So long as we keep the filename explicit, here. `.env` has uses _inside_ some apps – Ruby, PHP, and Node, at minimum, have packages for reading these in, which let the actual environment override what's listed in the file, so things like `DATABASE_HOSTNAME=$DATA_DB_HOST` wouldn't work properly if `.env` is assumed as a fallback.
