### ISSUE TITLE
Windows Vagrantfile syntax error

### ISSUE THREAD

**Issue by umurgdk** [nanobox-io/nanobox#52]
When i check Vagrant file i see directory separators aren't escaped. 
And i see syntax errors on vagrant.log.
nanobox.vm.synced_folder "C:\Users\umurgdk\Documents\myapp", "....."

to fix you need to add double backslashes.

OS: Windows 10

**Comment by umurgdk** [comment]
Relative line is there:
https://github.com/nanobox-io/nanobox/blob/master/util/vagrant/init.go#L27

```config.CWDir``` is populated by ```os.Getwd();``` in ```config/config.go```. Problem starts on Vagrantfile. Since vagrantfile is basically ruby code it understands ```C:\U...``` as like escaped character ```\U```. Im sorry i can't create a PR because I don't have a working go setup right now and never wrote go before.

**Comment by rajeevmehrotra** [comment]
+1 I see the same behavior in my vagrant.log as well:

`C:UsersMegit...`

**Comment by lyondhill** [comment]
@umurgdk I can create the pull request. Thanks for doing the leg work!
