### ISSUE TITLE
Network bridge error

### ISSUE THREAD

**Issue by hl** [nanobox-io/nanobox#531]
I'm having troubles starting Nanobox after today's update:

Nanobox Version 2.1.2-170817T1422 (c48c79c)

As you can see in the below recording I'm first getting a network bridge error.
https://asciinema.org/a/xXVLrSGwON9nCyNy2T2cIhTU9

I've done the following:
- nanobox implode
- manually removed all containers and images
- reset docker (config and image)

**Comment by sanderson** [comment]
Thanks for reporting @hl. We are aware of the bug and will have a fix for it in the next little bit. Sorry about the head-ache. Once the change is in, tested, and published, you'll need to run `nanobox-update` again to pull down the new version.

**Comment by hl** [comment]
Hey @sanderson, I can confirm it's working now, thanks @glinton  !
