### ISSUE TITLE
Windows nanobox destroy error

### ISSUE THREAD

**Issue by umurgdk** [nanobox-io/nanobox#54]
When i try to destroy a nanobox. It fails with:
+> Removing whyre-web.dev domain from /etc/hosts

And log says:
```2015-11-18 22:55:13 FATAL [commands/halt] - exec: "/bin/sh": file does not exist```

OS: windows 10

**Comment by sanderson** [comment]
Thx @umurgdk. We haven't had a chance to thoroughly test on Windows yet so the details help. We'll dig into this as soon as we can.

**Comment by tylerflint** [comment]
Yeah looks like this slipped through. /etc/hosts is platform specific, and obviously windows doesn't support it.

**Comment by lyondhill** [comment]
This issue was fixed in https://github.com/nanobox-io/nanobox/pull/91 but I forgot to update the issue
