### ISSUE TITLE
Add flag to `log` command to not strip original timestamp when printing logs

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#559]
```
Thu Aug 31 16:39:10 2017 logger.data.logvac (logvac[daemon]) ::  DEBUG Starting record cleanup batch...
```
In the log file there would have been a timestamp from the app itself (generally much more granular too)

**Comment by shie-erlich** [comment]
i'd suggest to consider making this behavior the default, at least for the UI version of things.
