### ISSUE TITLE
If the SSH folder doesnt exist vagrant up will fail

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox#57]
2015-11-19 14:07:30 ERROR There are errors in the configuration of this machine. Please fix
2015-11-19 14:07:30 ERROR the following errors and try again:
2015-11-19 14:07:30 ERROR 2015-11-19 14:07:30 ERROR vm:
2015-11-19 14:07:30 ERROR * The host path of the shared folder is missing: ~/.ssh
2015-11-19 14:07:30 ERROR 2015-11-19 14:08:26 ERROR There are errors in the configuration of this machine. Please fix
2015-11-19 14:08:26 ERROR the following errors and try again:
2015-11-19 14:08:26 ERROR 2015-11-19 14:08:26 ERROR vm:
2015-11-19 14:08:26 ERROR * The host path of the shared folder is missing: ~/.ssh
2015-11-19 14:08:26 ERROR

**Comment by rajeevmehrotra** [comment]
Shot in the dark here, but this may have to do with where the `.ssh` folder is expected to be.

For example, when I ran `nanobox dev` originally it said `See ~/.nanobox/nanobox.log for details`

I am using Windows, and the `~/` directory in this case turned out to be my user folder, so I found the log in:
`C:/Users/Me/.nanobox/nanobox.log`

Now, my `.ssh` folder is actually stored in my `C:/` directory, i.e. `C:/.ssh`.  

So using the logic from where the log is stored, perhaps ssh is expected to be in `C:/Users/Me/.ssh` when it is not

**Comment by lyondhill** [comment]
@rajeevmehrotra that is exactly right. I think to solve this issue nanobox needs to:
1 try detecting where ssh has put its folder
2 use that location to mount into the virtual box
3 if the location doesnt exist and cant be found dont try mouting the folder at all

**Comment by rajeevmehrotra** [comment]
@lyondhill I was able to fix this particular issue manually by editing the Vagrant file.

In particular, I went to `C:/Users/<Me>/.nanobox/apps/<MyApp>/Vagrantfile` and changed the `nanobox.vm.synced_folder` from `~/.ssh` to `C:\\.ssh`.  Note that I had to change single backslashes to double backslashes for windows directories.

After this fix I got a later error: 
`FATAL [util/file/hosts] os.Open() failed -  - open /etc/hosts: The system cannot find the path specified.` but this may already be filed under a separate issue, I'll look

**Comment by lyondhill** [comment]
the /etc/hosts file problem should be fixed in https://github.com/nanobox-io/nanobox/pull/76 which just got merged. The new nanobox cli should be uploaded soon.

**Comment by lyondhill** [comment]
@rajeevmehrotra do you know how I would detect in windows where the ssh folder is? on unix systems its pretty standard to put it in the ~/.ssh/ folder is C:\.ssh\ the 'standard' in windows?

**Comment by rajeevmehrotra** [comment]
I'm not sure if putting it at the C directory is standard, I can look into it.  My ssh setup was configured as I was installing the git cli, which allows for the option to use ssh (among other commands) to be invoked directly from window's command prompt, and which created the .ssh directory at the C level.  I would imagine this is a pretty typical setup, though I'm not sure what it would look like if I were to use ssh from cygwin or similar.

**Comment by rajeevmehrotra** [comment]
Also, when you say the new nanobox cli should be updated soon, does that mean that a `nanobox update` command will pull down the latest changes? Or to get the latest will I need to have installed nanobox from source rather than from the installer as I had done?

**Comment by tylerflint** [comment]
@rajeevmehrotra normally 'nanobox update' would suffice. Unfortunately, the binary that was available yesterday (which is probably when you downloaded it) has a bug where the 'update' isn't working properly. 

Go ahead and try 'nanobox update', and afterwards the version should be at least 0.16.8. If it's not, you'll need to download the installer and re-run. 

Thanks

**Comment by rajeevmehrotra** [comment]
@tylerflint thanks! nanobox update does not work (says its up to date). I'll redownload the installer and try again

**Comment by sdomino** [comment]
@rajeevmehrotra I'm not sure the installers have the newest version of nanobox just yet, you may need to download it from here: https://s3.amazonaws.com/tools.nanobox.io/cli/windows/amd64/nanobox.exe and replace your existing one

**Comment by rajeevmehrotra** [comment]
Thanks, I replaced the old `nanobox.exe` with the one downloaded from that link

I got this error:
```
FATAL Cause of failure: runtime error: makeslice: len out of range
2015-11-20 12:57:33 FATAL Error output:
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/main.go:24 (0x40110a)
/usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:437 (0x459275)
/usr/local/Cellar/go/1.5/libexec/src/runtime/panic.go:423 (0x42ae27)
/usr/local/Cellar/go/1.5/libexec/src/runtime/slice.go:26 (0x43eb14)
/usr/local/Cellar/go/1.5/libexec/src/strings/strings.go:464 (0x541386)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/util/file/file.go:197 (0x54858a)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/update.go:141 (0x48affc)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/commands/update.go:42 (0x489f65)
/Users/sdomino/godeps/src/github.com/spf13/cobra/command.go:547 (0x508420)
/Users/sdomino/godeps/src/github.com/spf13/cobra/command.go:630 (0x508d1a)
/Users/sdomino/gocode/src/github.com/nanobox-io/nanobox/main.go:38 (0x40108c)
/usr/local/Cellar/go/1.5/libexec/src/runtime/proc.go:111 (0x42d3be)
/usr/local/Cellar/go/1.5/libexec/src/runtime/asm_amd64.s:1696 (0x45b5b1)
```

**Comment by lyondhill** [comment]
@rajeevmehrotra i created a new issue for the new report #83 but that one should be a quick fix.
