### ISSUE TITLE
Support bash style comments in loaded vars file

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#577]
Support the following...

```
# this iz a comet
this="is a thing"
that="is
another
thing"

# comment after newline
so="is this"
i=m pretty sure this is supported too
sorry=only # comments starting newlines are considered comments here

# another comment
```

**Note:** only lines beginning with `#` will be considered comments, not `#` inline anywhere.

**Comment by danhunsaker** [comment]
```
this="is a thing" # followed by a comment
```

**Comment by glinton** [comment]
I'm not certain what the point of the last comment was, but the first line would likely break. the second line would be completely ignored because it is a valid nanobox evar file comment.

Again: **only lines beginning with `#` will be considered comments, not `#` inline anywhere.**

**Comment by danhunsaker** [comment]
Sorry, should have clarified. Those are additional scenarios I was proposing tests for, if not actually support. Not supporting inline comments is perfectly fine with me, and I do understand the "limitation".
