### ISSUE TITLE
Password protected ssh keys prompt is missing

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#578]
Currently, the `-v` flag must be passed to nanobox to view the prompt for password protected ssh keys. A patch has been pushed to make password protected keys an 'opt-in' feature until the display issue is resolved.

**Comment by tylerflint** [comment]
You might just be missing something like this: https://github.com/nanobox-io/nanobox/blob/master/processors/server/setup.go#L42-L45

**Comment by glinton** [comment]
Ah, possibly. I'll check it out, thanks. I haven't spent much time yet in the display package yet.
