### ISSUE TITLE
boot2docker appears to not have completed

### ISSUE THREAD

**Issue by binduwavell** [nanobox-io/nanobox#58]
I ran ```nanobox dev``` and it started setting things up. I noticed the boot2docker install seems to have stopped at 95%.

```
+> Installing nanobox/boot2docker...
   [**************************************    95%] 11.9M/s (0:00:01 remaining)   -
+> Creating a nanobox
```

Based on how much further the process went I'm guessing the progress bar was simply not updated at 100%

**Comment by tylerflint** [comment]
@sdomino Is this still happening?

**Comment by sdomino** [comment]
As far as I know this is still an issue.
