### ISSUE TITLE
specifying engine breaks when not a local development engine

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#59]
attempting to launch an app while specifying an engine, like 'java', the cli will fail because it can't find the path to the engine.

The correct behavior is for the cli to first check if the value matches a path on the local filesystem. If not, the cli should NOT fail and should NOT try to mount an engine.

Boxfile example:

```yaml

build:
  engine: java

```

Relevant log entry:

```txt
2015-11-19 10:09:04 ERROR stat java: no such file or directory
```

Also output:

```txt
[util/vagrant/init] engineutil.RemountLocal() failed (See ~/.nanobox/nanobox.log for details)
```

**Comment by sdomino** [comment]
resolved in #78
