### ISSUE TITLE
cannot evar load on remoate-alias

### ISSUE THREAD

**Issue by hyusetiawan** [nanobox-io/nanobox#597]
I am having an issue loading environment variables using load on remote-alias:
```
$ nanobox evar load app-staging ./etc/env/staging.txt

Error   : Failed to get var contents - Failed to read file - open app-staging: no such file or directory
Context : failed to load evars from file
```
but I am able to add using nanobox evar add perfectly fine, is this a known bug

**Comment by sanderson** [comment]
I'm wondering if there's an issue with the format/content of the file. I'm guessing it has sensitive values in it so it probably wouldn't be good to include here. Does it following the guidelines outlined here: https://docs.nanobox.io/cli/evar/#environment-variable-files

**Comment by hyusetiawan** [comment]
@sanderson yes it does, because I can use the load command on dry-run and local, same file. Only on to remote-alias where it fails

**Comment by glinton** [comment]
@hyusetiawan please paste the output of `nanobox remote ls`

**Comment by hyusetiawan** [comment]
$ nanobox remote ls

App Name          : Alias
--------------------------
app-staging  : default

**Comment by glinton** [comment]
The `nanobox evar load --help` tells your solution. Use the alias, "default" or none at all.

**Comment by glinton** [comment]
"default" as it's in the 'alias' column. It's a default that we create.
