### ISSUE TITLE
Copying ssh keys into the build environment...

### ISSUE THREAD

**Issue by houmanka** [nanobox-io/nanobox#599]
When I run `nanobox run` 

> I get Copying ssh keys into the build environment...

It is trying to override on one of the key in my .ssh folder. Very strange. 
Why do you think it is happening?

**Comment by danhunsaker** [comment]
Since everything Nanobox runs is run inside one or more containers, we have to copy your SSH keys into your containers in order for your apps to have access to them. These keys are _never_ placed anywhere that will see them leave your own computer, though, so there's not a security concern from that.

**Comment by houmanka** [comment]
Error   : failed to execute hook (user) on 19c46ba52f448326d61df4e49d62777a22c71c81d6566729284a306846ce8c54: util:Exec:/opt/nanobox/hooks/user: bad exit code(1):
Context : failed to build the code -> failed to run the (build)user hook

**Comment by houmanka** [comment]
So do I need to give 777 permission to my files in .ssh folder?

**Comment by danhunsaker** [comment]
No, that would break all sorts of things. Let's dig in and get more details on what the actual error is. Can you re-run the `nanobox` task with `-v` added to it, then paste the entire output here?

**Comment by houmanka** [comment]
```
Building runtime :
  Starting docker container :
  Preparing environment for build :
    - Copying ssh keys into the build environment...

    ! FAILED TO /DATA/VAR/HOME/GONANO/.SSH/CADDIECHALLENGE COPY.PEM.TXT !

    Exit
     1

    Command
     chown gonano:gonano /data/var/home/gonano/.ssh/caddiechallenge copy.pem.txt

    Output
     chown: cannot access '/data/var/home/gonano/.ssh/caddiechallenge': No such file or directory
     chown: cannot access 'copy.pem.txt': No such file or directory


Error   : failed to execute hook (user) on b639317ae8f75348d08625f33b60f163cf1b5997422ea30b7e8e6784f3d5975c: util:Exec:/opt/nanobox/hooks/user: bad exit code(1):
Context : failed to build the code -> failed to run the (build)user hook
```

**Comment by houmanka** [comment]
caddiechallenge is an application that I developed longtime ago and has nothing to do with my current project.

**Comment by danhunsaker** [comment]
Oh. Huh. It isn't properly quoting the filenames to avoid issues with spaces.

The fix here is to rename any files in your `~/.ssh` so they don't have spaces, at least until we can fix that behavior.

**Comment by houmanka** [comment]
Thanks. I never put space in my files, the one in there was dummy file, so I deleted. All good now. Thanks
