### ISSUE TITLE
Local engine doesn't get copied or used

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox#603]
Example boxfile.yml: (`·` represent space)
```
run.config:
··engine:·../python·
```

**Comment by glinton** [comment]
Turns out the sync fails even without a space and with the proper path.
```
    - Copying engine :
       sync:               0 100%    0.00kB/s    0:00:00 (xfr#0, to-chk=0/1)
```

**Comment by danhunsaker** [comment]
Trailing whitespace should always be removed, everywhere. I mean, we shouldn't have to strip it ourselves, but still. Trailing whitespace is anathema.

**Comment by glinton** [comment]
Yes, turns out it is has nothing to do with this issue though. I falsely assumed my first run (with no trailing whitespace) worked. Since the hooks [handle and parse the boxfile](https://github.com/nanobox-io/nanobox-docker-build/blob/20ee07b2db6ec3ec83ecad632508ca09d115a545/files/opt/nanobox/hooks/lib/boxfile.rb) my guess is nanobox isn't mounting in the engine to be rsynced from the specified location.

It is planned to incorporate the boxfile validation in nanobox itself, so as to save time before finding out a bad node was entered, but there is much in the plans (so no solid ETA).
