### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by vahagnaharonian** [nanobox-io/nanobox#61]
Can't find a way to uninstall this on Mac. Installed using Native Installer with Vagrant and VirtualBox.

The uninstaller described [here](https://docs.nanobox.io/installation/uninstalling/) isn't present anywhere.

**Comment by sanderson** [comment]
Thanks for reporting @vahagnaharonian. I'll have @glinton take a look. He manages the installers/uninstallers.

**Comment by kwhitaker** [comment]
:+1: I also can't find the uninstaller in the package file.

**Comment by adityadalal924** [comment]
For now, you can download and run [`.uninstall.tool`](https://github.com/nanobox-io/nanobox-installer/blob/master/darwin/dmg/.uninstall.tool) - it's a bash shell script.

If you installed with Homebrew Cask (ie. `brew install nanobox`), you can just run `brew zap nanobox`. (The only part of the above script that won't be run is removing the related boxes)
ie.
```bash
vagrant box list  | grep '^nanobox/boot2docker ' &> /dev/null
if [[ $? -eq 0 ]]; then
    vagrant box remove nanobox/boot2docker --force &> /dev/null
fi
```

**Comment by vahagnaharonian** [comment]
@adityadalal924 that script didn't work, got this error:

```
The uninstallation process requires administrative privileges
because some of the installed files cannot be removed by a
normal user. You may now be prompted for a password...

107:114: syntax error: Expected “given”, “with”, “without”, other parameter name, etc. but found identifier. (-2741)
An error must have occurred since a file that was supposed to be
removed still exists: /opt/nanobox
```

But thanks anyway for it. I deleted those files manually.

**Comment by adityadalal924** [comment]
@vahagnaharonian I don't maintain the script, I just saw it and thought it might be useful.

**Comment by glinton** [comment]
It was a design decision to leave the uninstaller out of the `.dmg` file, but it is still there, just hidden. It should be accessible at `/Volumes/nanobox/.uninstall.tool` when the dmg is mounted. I'll be releasing a new dmg today that has a fix for the issue @adityadalal924 mentioned.

**Comment by mbana** [comment]
How do I uninstall this?

I've also noticed some containers aren't stopped.

**Comment by danhunsaker** [comment]
First, run `nanobox implode` to clear out the VM, if we created one, and any Nanobox containers, along with any settings or configuration. Then, run the uninstall tool mentioned above.
