### ISSUE TITLE
Nanobox-machine executable file not found in %PATH% (Windows 10)

### ISSUE THREAD

**Issue by bloodbank** [nanobox-io/nanobox#623]
After installing Nanobox with administrator rights, running the "nanobox" command yields nothing but an error for "not recognized as an internal or external command".

Running the executable from the whole path, ie. "c:\program files\nanobox\nanobox.exe" run, just stalls for a bit on "! Launching VM" and then this error;

```
Error   : : exec: "nanobox-machine": executable file not found in %PATH%
Context : failed to create the provider
```

Should probably be fixed with the installer.

**Comment by danhunsaker** [comment]
Indeed, the installer should check whether it was started with Admin rights already in place, and refuse to continue. It will escalate for any actions it needs escalation for automatically, but it can't configure your user's regular PATH if you don't start your install from there. Try uninstalling, then reinstalling with normal permissions.

**Comment by bloodbank** [comment]
Manually added it to the PATH for my user account, now it works. Thanks

**Comment by danhunsaker** [comment]
Glad it's working. If you encounter any other issues, though, try the above before anything else. We don't support installing (or running, for that matter) with admin privileges already in place.
