### ISSUE TITLE
Do not break homebrew cask and other automated installations

### ISSUE THREAD

**Issue by tpetry** [nanobox-io/nanobox#624]
Installing software with brew is an essential task for everyone developing on Mac OS and it's nice nanobox got a recipe with #40. But the problem is that the hash of the deployed release is changing every few days breaking the ability to install nanobox because it is pinned for security reasons. 

Four days ago i reported that the hashsum at homebrew cask for the 2.3.0 release was wrong (caskroom/homebrew-cask#41589) and as of today the installation fails again while the hash has changed again. And this for the stable distributed release 2.3.0.
Please stop replacing the published release all the time to allow unsupervised installations for **ANY** automated system which has to check the hash for security reasons.

**Comment by danhunsaker** [comment]
We no longer support homebrew installs, or indeed installation via _any_ system package manager, as mentioned in the final comment on the issue linked above. Accordingly, the cask should be removed, or at least include a disclaimer to users not to expect it to work consistently.

**Comment by tpetry** [comment]
You will have good reasons for this decision but you should think about it a second time:
The only left option would be the steps of your [Continuous Integration & Deployment Workflow](https://docs.nanobox.io/workflow/ci-cd/). And to keep my possible large message short i have to say that the pointed out method of simply running some (untrusted) bash script within a CI workflow is not permitted for any project/company with security people involved because you could change the script all the time. And it could be malicious tomorrow because you've decided to do it, some MITM, someone replaced the file on S3 and so on and so on.

**Comment by danhunsaker** [comment]
We don't support installation via automated methods at all outside of the continuous integration convenience script mentioned above, which is merely a convenience, as mentioned presently. We simply don't have the resources to maintain alternative installation mechanisms.

**Comment by tpetry** [comment]
You don't need any resources to maintain alternative installation mechanisms. The actual ci.sh does not do more than installing and configuring docker and downloading https://s3.amazonaws.com/tools.nanobox.io/nanobox/v2/linux/amd64/nanobox.

If you simply have stable files at this url or another one the automated secure ci installation can be done by everyone without any problem - without you maintaining anything.
