### ISSUE TITLE
Vi resizes console window when in a nanobox dev

### ISSUE THREAD

**Issue by lyondhill** [nanobox-io/nanobox#63]

**Comment by binduwavell** [comment]
I'm on a Mac running latest OS. I use iTerm (latest). I have a HUD window triggered by Cmd-Space. The HUD is 49 rows tall and 202 columns wide.

I create a new folder "nano" with a Boxfile containing three lines:
```
build:
  engine: ../nanobox-engine-java
  stability: beta
```

I run ```nanobox dev``` to get a shell, I wail on the return key and see that I have access to all 49 rows.

I run ```vi Boxfile``` and the editor is only 25 rows high, the window is still 49 rows high. I expect vi to be 49 rows high.

I exit vi and exit the nanobox. The terminal is still limited to 25 rows even though the window is still 49 rows high.
