### ISSUE TITLE
Windows 7: nanobox run failed to setup the network bridge

### ISSUE THREAD

**Issue by flm-berlin** [nanobox-io/nanobox#634]
Hello,

i am running Nanobox Version 2.3.0-171214T1632 (6239a4e) on Windows 7 Professional (64 bit) with VirtualBox Version 5.2.4 r119785.

On command "nanobox run" the following error message is shown:

`Administrator privileges are required to start the server.
Another window will be opened as the Administrator and permission may be request
ed.
Enter to continue:

Start-Process : Zugriff verweigert
Bei Zeile:1 Zeichen:17
+ & {Start-Process <<<<  'cmd' -ArgumentList '/c C: & cd C:\Users\a\b & "E:\Program Files\Nanobox\nanobox.exe" env server start' -Verb RunAs -W
ait}
    + CategoryInfo          : NotSpecified: (:) [Start-Process], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.P
   owerShell.Commands.StartProcessCommand

V Skipping (already running)
Building bridge :
  V Configuring

Error   : dial tcp 127.0.0.1:23456: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.
Context : failed to setup the network bridge

Enter to continue:`

I tried to uninstall/install nanobox & virtual box several times but the error always occurs.

**Comment by sanderson** [comment]
@flm-berlin Nanobox requires Windows 10+. Although it could possibly work on Windows 7, we don't test for it nor support it.

Here's the system requirements in the Nanobox installation documentation: https://docs.nanobox.io/install/#system-requirements
