### ISSUE TITLE
how to install npm packages globally inside a nanobox container?

### ISSUE THREAD

**Issue by hadihallak** [nanobox-io/nanobox#654]
i would make an npm package globally available , adonisjs/cli in particular.

**Comment by danhunsaker** [comment]
So long as you have `node_modules/.bin` in your `extra_paths`, every package you install is effectively global. Each project gets its own containers, so if you're looking for a way to have a module preinstalled across all of them by default, we don't currently have one.

**Comment by hadihallak** [comment]
Awesome! thanks for the help.
