### ISSUE TITLE
SHA-256 hash changed for .pkg file for version 2.3.0

### ISSUE THREAD

**Issue by gtmgianni** [nanobox-io/nanobox#662]
According to the [releases page](https://github.com/nanobox-io/nanobox/releases), there hasn't been a version bump from `2.3.0`, but the SHA-256 hash for its `.pkg` file [(link)](https://s3.amazonaws.com/tools.nanobox.io/installers/v2/mac/Nanobox.pkg) has changed.

[For the purpose of this pull request](https://github.com/caskroom/homebrew-cask/pull/46853), can I confirm that this change was legitimate?

**Comment by danhunsaker** [comment]
The change is legitimate, yes, and a similar one is likely to happen again at some point. We don't support installation via any package repository, however, so it would be better served by replacing the package with a deprecation notice and/or a link to download the package directly from https://dashboard.nanobox.io/download

**Comment by gtmgianni** [comment]
Thank you @danhunsaker, I'll update my pull request.
