### ISSUE TITLE
nanobox 2.3.0: `nanobox deploy` command never ends

### ISSUE THREAD

**Issue by pablorsk** [nanobox-io/nanobox#675]
With previus deployed apps, nanobox 2.3.0 nevers ends deployment. Allways block on `Syncing app over previous deploy...`

```
$ nanobox deploy myapp -vvv
Root privileges are required to start the server. Your system password may be requested...
[sudo] password for user: 
Skipping (already running) :
Preparing environment :

Compiling application :
  Starting docker container :
  Preparing environment for compile :
    - Copying ssh keys into the build environment...
    - Setting up directories and permissions...
  Compiling code :
    - Cleaning up any previous releases...
    - Copying code...
    - Moving build into live code directory...

Deploying app :
  Starting docker container :
  Uploading :
    - Copying ssh keys into the build environment...
    - Syncing app...
    - Extracting app from previous deploy...
    - Syncing app over previous deploy...
```

Also, I try with `nanobox destroy` / `nanobox implode`

**Comment by pablorsk** [comment]
(by danhunsaker) 

There are so many factors in the speed of a deploy sync it's hard to say what's causing a specific slowdown in a specific moment.

Internet connection speed, both maximum and what's left after everything else using that same connection. Routing quality, and the quality/speed of each hop. Server load has a huge impact on both the processing speed of incoming packets, and other tasks related to evaluating each file to see which ones need transferred. The amount and nature of the exact changes has an impact on what needs transferred to begin with. The number of files involved in a sync, on both ends, has an impact. System load on the computer you deploy from. A few other things that aren't coming to mind, so are probably pretty rarely a thing that can be monitored or controlled.

I'd be sure to include any version control files in your `.nanoignore`, to prevent them from being in the final sync. (So a line with `.git/`, for example.) I tend to also include directories I've added to `network_dirs` entries, since their contents will just be replaced with whatever's in network storage anyway, and local use can/does put files in those locations. Avoid making major, sweeping changes to several files at once, if possible. Deploy from locations with very fast connections to the Internet, preferably via hardwire rather than wireless (wireless interference slows _everything_ down).

**Comment by pickettd** [comment]
I just hit this issue on Windows 10. I let it sit on the `Syncing runtime over previous deploy...` step for close to 2 hours. I have previously deployed this app from MacOS without a problem. Could it be an issue with trying to deploy now from a different platform?

```
$ nanobox deploy purple-code -t -v --debug
Preparing environment :
  Mounting codebase :

Compiling application :
  Starting docker container :
  Preparing environment for compile :
    - Copying ssh keys into the build environment...
    - Setting up directories and permissions...
  Compiling code :
    - Cleaning up any previous releases...
    - Copying code...
    - Moving code into app directory...

Deploying app :
  Starting docker container :
  Uploading :
    - Copying ssh keys into the build environment...
    - Syncing app...
    - Extracting app from previous deploy...
    - Syncing app over previous deploy...
       Syncing app: Warning: Permanently added '[104.248.69.83]:1567' (RSA) to the list of known hosts.
    - Committing app...
    - Syncing runtime...
    - Extracting runtime from previous deploy...
    - Syncing runtime over previous deploy...
```

**Comment by danhunsaker** [comment]
The change in platform shouldn't affect anything at all, since everything is being run from within the container, which is always Linux.

More likely, there's a difference in connection speed, number of files needing synced, or something on the server itself (rather than the computer you're deploying from) that's slowing things down. I'd check the server's resources and make sure it has plenty to work with. More details in my Slack comment which was reposted above.
