### ISSUE TITLE
TLS handshake error

### ISSUE THREAD

**Issue by ayushsharma82** [nanobox-io/nanobox#682]
Hi,

I keep getting this line after one hour or so in logs:
`TLS handshake error from 62.32.81.83:17927: tls: first record does not look like a TLS handshake`
The IP address and port in the line keeps changing time to tome.
and also what does this means? I can access my app on internet with SSL enabled.

Config:
Engine: Nodejs 
Using Express as http server and Nginx as Proxy
SSL: Let's Encrypt

**Comment by ayushsharma82** [comment]
Update: The above error is coming from `mesh.data.protocol`

**Comment by danhunsaker** [comment]
`mesh.data.portal` is your load balancer. This error just says something from `62.32.81.83` attempted to connect to your app on port 443, but wasn't using HTTPS to do it. This isn't an error within your application, and unless you own something at that source address, it's not an error you can even fix. It is, however, entirely harmless.

**Comment by ayushsharma82** [comment]
So, i figured out that one of the ip was my home's and other one was coming from `actions on google` server. I am using nginx to redirect all http to https requests.

**Comment by ayushsharma82** [comment]
This seems like a very general error. I will reopen the issue if it becomes serious.
