### ISSUE TITLE
Debian Package Installer has permissions error message on install

### ISSUE THREAD

**Issue by audieleon** [nanobox-io/nanobox#70]
With the native installer available on https://desktop.nanobox.io/downloads/ if I try to install either the bundle with the check box selected or unselected, I get the following error on Ubuntu 15.10:

><b>The package is of bad quality</b>
>The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.

>Details:
>The package doesn't provide a valid Installed-Size control field. See Debian Policy 5.6.20.

**Comment by lyondhill** [comment]
Good find. Thanks. I will let @glinton know
