### ISSUE TITLE
support http_proxy

### ISSUE THREAD

**Issue by mattn** [nanobox-io/nanobox#72]
it seems that run curl command to get nano-server.md maybe. but i'm on proxy environment.

**Comment by tylerflint** [comment]
Does anybody have any familiarity with configuring a proxy on linux?

@glinton @notxarb ?

**Comment by glinton** [comment]
@mattn can you define your problem/goal a little bit more? What is your environment like and what would you like to see happen?

**Comment by mattn** [comment]
```
$ nanobox dev
```
At the first, AFAIK, vagrant create new docker VM and getting nanobox image. But my network environment can't get the image. So I hope to pass environment variable http_proxy/https_proxy/http_proxy_user/http_proxy_pass into the docker VM.

**Comment by glinton** [comment]
Ok, I think we can make that happen.  And I assume you are able to fetch the vagrant [box](https://atlas.hashicorp.com/nanobox/boxes/boot2docker) from within your network environment (`vagrant box add nanobox/boot2docker`)?

**Comment by mattn** [comment]
In my understanding, on windows nanobox run on boot2docker. And it seems the init script is downloading something from AWS.

**Comment by tylerflint** [comment]
@glinton, @lyondhill: Can we find out if nanobox v1 works within a proxy network?

**Comment by glinton** [comment]
From what I've read, I think this issue can be resolved, since we no longer use vagrant, the proxy vars should work. It is on my list of things to test/verify though before I close this.

**Comment by lyondhill** [comment]
@mattn if this is still an issue feel free to reopen
