### ISSUE TITLE
Wrong architecture 'amd64' 

### ISSUE THREAD

**Issue by Revod** [nanobox-io/nanobox#77]
Hi, I have a ubuntu 32 bit and I like the idea of nanobox and donwload the **nanobox-bundle.deb** from the website but when I open the .deb get:

```
Wrong architecture 'amd64' 
```

**Comment by lyondhill** [comment]
Thanks for letting us know. Apparently our downloader just defaults to 64bit. We should have alternative links for different architectures. @Tolmark12

**Comment by Revod** [comment]
Where I can download the 32bit?

**Comment by sdomino** [comment]
@Revod try this link here https://s3.amazonaws.com/tools.nanobox.io/cli/linux/386/nanobox (don't forget to chmod 755 and stick it in your path)

**Comment by sdomino** [comment]
@Revod did that version of the CLI work for you?

**Comment by Revod** [comment]
sorry for the late reply, I download the file but it is not the complete
bundle like the web link

**Comment by lyondhill** [comment]
@Revod the file is just the executable. but s3 didn't retain the permissions so you have to 'chmod +x nanobox' then mv it to somewhere in your path.

**Comment by glinton** [comment]
Just so you know, the only thing you can do with the 32 bit cli is develop engines. The box we use in virtualbox is 64 bit and won't be able to start on other architectures.

**Comment by Revod** [comment]
Oh, thanks
