### ISSUE TITLE
abort if vagrant or virtualbox is too old

### ISSUE THREAD

**Issue by tylerflint** [nanobox-io/nanobox#80]
This is a trending issue. We need to figure out what is the earliest version that still works for both of these.

**Comment by sdomino** [comment]
@glinton do you happen to have an idea what minimum versions of each we might want to support? my thought was just start with whats currently out and set that as the first baseline

**Comment by sdomino** [comment]
This has been resolved here (https://github.com/nanobox-io/nanobox/pull/86)
