### ISSUE TITLE
Package Operation Fails on Bundle Install (Ubuntu15.10)

### ISSUE THREAD

**Issue by audieleon** [nanobox-io/nanobox#88]
When installing the bundle that includes Vagrant and VirtualBox on Ubuntu 15.10, the Package Operation fails with this message:

>(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 245198 files and directories currently installed.)
Preparing to unpack /tmp/nanobox-bundle.deb ...
Unpacking nanobox-bundle (0.16.9) over (0.16.9) ...
Setting up nanobox-bundle (0.16.9) ...
Selecting previously unselected package virtualbox-5.0.
dpkg: considering removing virtualbox in favour of virtualbox-5.0 ...
dpkg: no, cannot proceed with removal of virtualbox (--auto-deconfigure will help):
 virtualbox-dkms depends on virtualbox (>= 5.0.4-dfsg-2)
  virtualbox is to be removed.

>dpkg: regarding .../nanobox/share/virtualbox.deb containing virtualbox-5.0:
 virtualbox-5.0 conflicts with virtualbox
  virtualbox (version 5.0.4-dfsg-2) is present and installed.

>dpkg: error processing archive /opt/nanobox/share/virtualbox.deb (--install):
 conflicting packages - not installing virtualbox-5.0
Errors were encountered while processing:
 /opt/nanobox/share/virtualbox.deb
dpkg: error processing package nanobox-bundle (--install):
 subprocess installed post-installation script returned error exit status 1
dpkg: error: failed to remove my own update file /var/lib/dpkg/updates/0000: No such file or directory

It appears that if the version of a package is later than the one supplied (in this case VirtualBox 5.0.4 over the supplied version 5.0), then the installation fails. 

Is it possible for the installer to recognize and accept more recent packages of dependencies, as long as Nonobox's needs are met?

On a side note, the un-bundled version installed OK - great job on those last two bugs. Thank you.

**Comment by glinton** [comment]
I've changed the way the bundle installer works on linux.  It's now a tarball with a script that will install the bundled software individually (assuming it's being run on the correct linux version), rather than a 'nanobox-bundle' meta package.
