### ISSUE TITLE
nanobox dev fails due to permission needed to modify /etc/hosts and /etc/exports files

### ISSUE THREAD

**Issue by audieleon** [nanobox-io/nanobox#89]
With a fresh install of nanobox, I attempted to start a development environment for a Go project. 

Here is the console output:  
[nanoboxdev.txt](https://github.com/nanobox-io/nanobox/files/42343/nanoboxdev.txt)

And here is the log output:
[vagrant.log.txt](https://github.com/nanobox-io/nanobox/files/42346/vagrant.log.txt)

Am I doing something wrong? If you need any more information, let me know, and I'll get back to you as quickly as possible.

Ah, almost forgot: I am using a standard Ubuntu 15.10 64 bit install and the most basic install of Go outlined here: https://golang.org/doc/install  (I tried to start the dev machine in the folder for the Hello, World program used to test the Go install on that page)

**Comment by tylerflint** [comment]
Would you mind providing the contents of the Vagrantfile located in the same directory as the vagrant.log as previously provided?

Thanks!

**Comment by audieleon** [comment]
Here it is:
[Vagrantfile.txt](https://github.com/nanobox-io/nanobox/files/42378/Vagrantfile.txt)

**Comment by tylerflint** [comment]
Oh, looking at your vagrant.log... it appears that you don't have a .ssh directory in your home directory, or that it can't be read. 

Can you confirm that you don't have a ~/.ssh directory?

**Comment by tylerflint** [comment]
Regardless of what you find, that's certainly a scenario that hadn't been considered. We'll need to conditionally mount .ssh if it actually exists.

**Comment by tylerflint** [comment]
The workaround for right now would be do just create the directory. mkdir -p ~/.ssh 

Otherwise I'm sure we can get this fix in tomorrow or the day.

**Comment by audieleon** [comment]
Ok. Making the ~/.ssh file got me slightly different messages:

Console output:
>audieleon@thinkPad:~/GoWork/src/github.com/audieleon/hello$ nanobox dev
+> Created /home/audieleon/.nanobox/apps/hello/vagrant.log
+> Created /home/audieleon/.nanobox/apps/hello/server.log
+> Creating a nanobox
+> Nanobox may require admin privileges to modify your /etc/hosts and /etc/exports files.
[sudo] password for audieleon: 

>   - Importing nanobox base image....A vagrant error occured (See /home/audieleon/.nanobox/apps/hello/vagrant.log for details)
A vagrant error occured (See /home/audieleon/.nanobox/apps/hello/vagrant.log for details)
A vagrant error occured (See /home/audieleon/.nanobox/apps/hello/vagrant.log for details)
A vagrant error occured (See /home/audieleon/.nanobox/apps/hello/vagrant.log for details)
A vagrant error occured (See /home/audieleon/.nanobox/apps/hello/vagrant.log for details)

>A fatal Vagrant error occurred (See /home/audieleon/.nanobox/apps/hello/vagrant.log for details). Exiting...audieleon@thinkPaaudieleon@thinkPad:~/GoWork/src/github.com/audieleon/hello$ BB
BB: command not found

Vagrantfile and Log:
[Vagrantfile.txt](https://github.com/nanobox-io/nanobox/files/42393/Vagrantfile.txt)
[vagrantlog.txt](https://github.com/nanobox-io/nanobox/files/42394/vagrantlog.txt)

Looks like I'm missing something called nfsd. Tried to do apt-get on this and that didn't work (using the base install of Ubuntu)

Happy to do more testing for you. Just let me know.

**Comment by audieleon** [comment]
Tried adding he ~/.ssh file and that did help. Now it looks like I'm missing a dependency call "nfsd"

Details in the log and vagrant file:
[vagrantlog.txt](https://github.com/nanobox-io/nanobox/files/42398/vagrantlog.txt)
[Vagrantfile.txt](https://github.com/nanobox-io/nanobox/files/42399/Vagrantfile.txt)

I tried to install the nfsd dependency with apt-get, but it's not available with the sources I have setup (very little different from the base Ubuntu install)

Happy to do more testing for you, just let me know.

**Comment by audieleon** [comment]
Did a little more research, and found this: https://help.ubuntu.com/12.04/serverguide/network-file-system.html

Tried to install this, and got this message at the end of the install:
>Processing triggers for man-db (2.7.4-1) ...
Processing triggers for systemd (225-1ubuntu9) ...
Processing triggers for ureadahead (0.100.0-19) ...
ureadahead will be reprofiled on next reboot
Setting up nanobox-bundle (0.16.9) ...
Selecting previously unselected package virtualbox-5.0.
dpkg: considering removing virtualbox in favour of virtualbox-5.0 ...
dpkg: no, cannot proceed with removal of virtualbox (--auto-deconfigure will help):
 virtualbox-dkms depends on virtualbox (>= 5.0.4-dfsg-2)
  virtualbox is to be removed.

>dpkg: regarding .../nanobox/share/virtualbox.deb containing virtualbox-5.0:
 virtualbox-5.0 conflicts with virtualbox
  virtualbox (version 5.0.4-dfsg-2) is present and installed.

>dpkg: error processing archive /opt/nanobox/share/virtualbox.deb (--install):
 conflicting packages - not installing virtualbox-5.0
Errors were encountered while processing:
 /opt/nanobox/share/virtualbox.deb
>dpkg: error processing package nanobox-bundle (--configure):
 subprocess installed post-installation script returned error exit status 1
E: Sub-process /usr/bin/dpkg returned an error code (2)
audieleon@thinkPad:~/GoWork/src/github.com/audieleon/hello$

**Comment by sdomino** [comment]
We added a check to see if the ssh file exists before attempting to mount it here (https://github.com/nanobox-io/nanobox/pull/99/files#diff-7dfdb904f072f36a015953e68b4228fdR45) so that should resolve the first portion of this issue.

As for the second issue, we try to mount your directories in as NFS, but since you don't have what is needed to do that it fails. I've created this issue (https://github.com/nanobox-io/nanobox/issues/102) in which we will check for NFS before we try and use it. In the mean time you can create a nanofile (https://docs.nanobox.io/getting-started/nanofile/) and inside there specify:
```
mount_nfs: false
```
