### ISSUE TITLE
nanobox didn't see my Boxfile

### ISSUE THREAD

**Issue by harobed** [nanobox-io/nanobox#95]
In my folder, I've ```Boxfile``` : 

```
$ ls -l
total 12
-rw-r--r-- 1 stephane staff  80 nov 25 00:13 Boxfile
-rw-r--r-- 1 stephane staff 145 nov 23 12:09 app.py
-rw-r--r-- 1 stephane staff   6 nov 23 12:09 requirements.txt
```

When I execute nanobox dev, It's say : 

```
+> Detecting app language & engine
+> LANGUAGE AND ENGINE DETECTED [√]
   --------------------------------
   [√] LANGUAGE : python
   [√] ENGINE   : python (generic)
   --------------------------------
   NOTE : This is a generic python engine. It's likely you will need to
   configure your nanobox environment to suit your app via the Boxfile[1].
   If you're willing to answer a few questions about configuring and
   running this particular app, it's a quick and simple process to create
   an engine specific to your app or framework. So contact us and let's
   get this rolling!
```

I think that nanobox didn't see my ```Boxfile```, why ?

Best regards,
Stephane

**Comment by glinton** [comment]
@harobed we just published the python engine again which should contain the fix for this. Could you please try again and let us know if you are still having these issues? Thanks.

**Comment by harobed** [comment]
After : 

```
$ git clone https://github.com/nanobox-io/nanobox-python-sample.git
$ cd nanobox-python-sample
$ nanobox destroy
$ nanobox  update
$ nanobox update-images
$ nanobox dev
```I've always : 

```
+> Deploying codebase...
+> Detecting app language & engine
+> LANGUAGE AND ENGINE DETECTED [√]
   --------------------------------
   [√] LANGUAGE : python
   [√] ENGINE   : python (generic)
   --------------------------------
   NOTE : This is a generic python engine. It's likely you will need to
   configure your nanobox environment to suit your app via the Boxfile[1].
   If you're willing to answer a few questions about configuring and
   running this particular app, it's a quick and simple process to create
   an engine specific to your app or framework. So contact us and let's
   get this rolling!
   [1] http://engines.nanobox.io/engines/
   --------------------------------
   IRC   : #nanobox (freenode)
   EMAIL : engines@nanobox.io
   --------------------------------
+> Copying code into build container...
```

I don't know if I use the last python engine.

Suggest : with -v, display the commit id of engine used to see the version.

**Comment by sdomino** [comment]
I think what we'll do is if nanobox detects that you're using a local engine (even if it is a fork of the generic engine) it will just show the path to where it pulled the engine from. That way it will be very clear that you're using the correct engine.

**Comment by sdomino** [comment]
this will be addressed in https://github.com/nanobox-io/nanobox/issues/101
