### ISSUE TITLE
nanobox run fails to handle mysql

### ISSUE THREAD

**Issue by wdiechmann** [nanobox-io/nanobox#96]
Added a log at https://gist.github.com/wdiechmann/323dd78e83e34e87660c 

Got there doing:

  - rails new
  - cd rails
  - nanobox run
  ( would have expected nanobox to build me a vm running rails and another running mysql)
  - nanobox fails
  - gem install mysql (as suggested)
  - nanobox run
  - nanobox fails

and here I am

**Comment by lyondhill** [comment]
@wdiechmann thanks for reporting this. The engine that was detected was '[√] ENGINE   : ruby (generic)' I bet that is functionality that will be in the rails engine. @glinton would know more

**Comment by wdiechmann** [comment]
great - so should I address @glinton directly - or sit quietly - or try my luck with editing the Boxfile - adding 

    build:
      engine: "rails"

**Comment by lyondhill** [comment]
he should have gotten an email when i referenced him in my comment. He should get back to us shortly

**Comment by glinton** [comment]
Currently we do not have a rails engine, but it is planned. Currently you will have to specify the services your app requires in your Boxfile [here is an example](https://gist.github.com/tylerflint/09389e3cfdb12fa57225) the ruby engine should install the mysql client if you specify `mysql1` in place of that `postgresql1`.

**Comment by wdiechmann** [comment]
perfect - I'll report back how it fares - thx a mill for your prompt attention @lyondhill and @glinton 

FYI I plan to use nanobox to build container-packs to distribute to subcontractors building parts of a heterogeneous environment comprising an M$ Dynamics AX, M$ SQL, IIS, NGINX, Rails, Redis, PubNub service and Android 4.1 app collecting salestruck data

**Comment by wdiechmann** [comment]
I'm afraid that did not cut the mustard :(

updated the gist  https://gist.github.com/wdiechmann/323dd78e83e34e87660c

and now puma is squeezing itself into the mix - and not with any kind words ;)

I added a Boxfile in the project root - with this:
```
build:
  webserver: puma

web1:
  name: web

worker1:
  name: workerz

redis1:
  name: queue

mysql1:
  name: db
```

**Comment by tylerflint** [comment]
It looks like there was a copy/paste error in the engine service detection logic. The engine has been published with the fix. The docker build image should be updated within the hour. You'll need to update the docker images and then force a rebuild:

```bash
$ nanobox update-images
$ nanobox dev --rebuild
```

Thanks!

**Comment by sdomino** [comment]
https://github.com/nanobox-io/nanobox-engine-ruby/commit/ac649a6a421fdf43b842a38cdfc79189951fd7bb

**Comment by wdiechmann** [comment]
@tylerflint - oh no; It's me thanking you guys!
